# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MsgMail.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import MsgCode_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='MsgMail.proto',
  package='ProtoNet',
  serialized_pb='\n\rMsgMail.proto\x12\x08ProtoNet\x1a\rMsgCode.protoB\x19\n\x17\x63om.version.protobuf.pb')





DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\027com.version.protobuf.pb')
# @@protoc_insertion_point(module_scope)
