//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: MsgCode.proto
namespace ProtoNet
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResponseResult")]
  public partial class ResponseResult : global::ProtoBuf.IExtensible
  {
    public ResponseResult() {}
    
    private int _code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int code
    {
      get { return _code; }
      set { _code = value; }
    }
    private bool _success;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"success", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool success
    {
      get { return _success; }
      set { _success = value; }
    }
    private string _msg = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string msg
    {
      get { return _msg; }
      set { _msg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerAccount")]
  public partial class PlayerAccount : global::ProtoBuf.IExtensible
  {
    public PlayerAccount() {}
    
    private int _type = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private double _count = default(double);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double count
    {
      get { return _count; }
      set { _count = value; }
    }
    private double _bankcount = default(double);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"bankcount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double bankcount
    {
      get { return _bankcount; }
      set { _bankcount = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResNotifyAlert")]
  public partial class ResNotifyAlert : global::ProtoBuf.IExtensible
  {
    public ResNotifyAlert() {}
    
    private string _msg;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string msg
    {
      get { return _msg; }
      set { _msg = value; }
    }
    private string _extendStr;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"extendStr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string extendStr
    {
      get { return _extendStr; }
      set { _extendStr = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResNotifyDissolutionConnect")]
  public partial class ResNotifyDissolutionConnect : global::ProtoBuf.IExtensible
  {
    public ResNotifyDissolutionConnect() {}
    
    private int _gameId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"gameId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gameId
    {
      get { return _gameId; }
      set { _gameId = value; }
    }
    private int _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private string _msg = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string msg
    {
      get { return _msg; }
      set { _msg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResNotifyChatArrive")]
  public partial class ResNotifyChatArrive : global::ProtoBuf.IExtensible
  {
    public ResNotifyChatArrive() {}
    
    private string _msgId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"msgId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string msgId
    {
      get { return _msgId; }
      set { _msgId = value; }
    }
    private int _msgType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"msgType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int msgType
    {
      get { return _msgType; }
      set { _msgType = value; }
    }
    private string _msg;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string msg
    {
      get { return _msg; }
      set { _msg = value; }
    }
    private int _chanel;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"chanel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int chanel
    {
      get { return _chanel; }
      set { _chanel = value; }
    }
    private long _msgCreateTime;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"msgCreateTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long msgCreateTime
    {
      get { return _msgCreateTime; }
      set { _msgCreateTime = value; }
    }
    private string _fromUniqueId;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"fromUniqueId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string fromUniqueId
    {
      get { return _fromUniqueId; }
      set { _fromUniqueId = value; }
    }
    private int _pos = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private string _fromControllerNick = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"fromControllerNick", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string fromControllerNick
    {
      get { return _fromControllerNick; }
      set { _fromControllerNick = value; }
    }
    private string _fromControllerHeadurl = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"fromControllerHeadurl", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string fromControllerHeadurl
    {
      get { return _fromControllerHeadurl; }
      set { _fromControllerHeadurl = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResChat")]
  public partial class ResChat : global::ProtoBuf.IExtensible
  {
    public ResChat() {}
    
    private ProtoNet.ResponseResult _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoNet.ResponseResult result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqChat")]
  public partial class ReqChat : global::ProtoBuf.IExtensible
  {
    public ReqChat() {}
    
    private int _msgType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"msgType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int msgType
    {
      get { return _msgType; }
      set { _msgType = value; }
    }
    private string _msg;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string msg
    {
      get { return _msg; }
      set { _msg = value; }
    }
    private int _chanel;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"chanel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int chanel
    {
      get { return _chanel; }
      set { _chanel = value; }
    }
    private string _toUniqueId = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"toUniqueId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string toUniqueId
    {
      get { return _toUniqueId; }
      set { _toUniqueId = value; }
    }
    private string _clubId = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"clubId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string clubId
    {
      get { return _clubId; }
      set { _clubId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResNotifyBeKickOut")]
  public partial class ResNotifyBeKickOut : global::ProtoBuf.IExtensible
  {
    public ResNotifyBeKickOut() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResExceptionCatch")]
  public partial class ResExceptionCatch : global::ProtoBuf.IExtensible
  {
    public ResExceptionCatch() {}
    
    private string _msg;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string msg
    {
      get { return _msg; }
      set { _msg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResConnectCreat")]
  public partial class ResConnectCreat : global::ProtoBuf.IExtensible
  {
    public ResConnectCreat() {}
    
    private long _now;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"now", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long now
    {
      get { return _now; }
      set { _now = value; }
    }
    private long _heartbeartTime;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"heartbeartTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long heartbeartTime
    {
      get { return _heartbeartTime; }
      set { _heartbeartTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqHeartBeat")]
  public partial class ReqHeartBeat : global::ProtoBuf.IExtensible
  {
    public ReqHeartBeat() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResHeartBeat")]
  public partial class ResHeartBeat : global::ProtoBuf.IExtensible
  {
    public ResHeartBeat() {}
    
    private long _time;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long time
    {
      get { return _time; }
      set { _time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"RoomType")]
    public enum RoomType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"GOLD_ROOM", Value=1)]
      GOLD_ROOM = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CARD_ROOM", Value=2)]
      CARD_ROOM = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MATCH_ROOM", Value=3)]
      MATCH_ROOM = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SHANGZHUANG_ROOM", Value=4)]
      SHANGZHUANG_ROOM = 4
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"GameCode")]
    public enum GameCode
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_GET_MATCH_LIST", Value=699999)]
      REQ_GET_MATCH_LIST = 699999,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_GET_MATCH_LIST", Value=699998)]
      RES_GET_MATCH_LIST = 699998,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_SIGNUP_MATCH", Value=699997)]
      REQ_SIGNUP_MATCH = 699997,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_SIGNUP_MATCH", Value=699996)]
      RES_SIGNUP_MATCH = 699996,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_NOTIFY_ENTER_MATCH", Value=699995)]
      RES_NOTIFY_ENTER_MATCH = 699995,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_CANLE_SIGN_MATCH", Value=699994)]
      REQ_CANLE_SIGN_MATCH = 699994,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_CANLE_SIGN_MATCH", Value=699993)]
      RES_CANLE_SIGN_MATCH = 699993,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_NOTIFY_MATCHROOM_WAITTING_CHANGE", Value=699992)]
      RES_NOTIFY_MATCHROOM_WAITTING_CHANGE = 699992,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_NOTIFY_TIMES_OVER", Value=699991)]
      RES_NOTIFY_TIMES_OVER = 699991,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_CONTINUE_MATCH", Value=699990)]
      REQ_CONTINUE_MATCH = 699990,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_CONTINUE_MATCH", Value=699989)]
      RES_CONTINUE_MATCH = 699989,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_GATE_LOGIN", Value=899999)]
      REQ_GATE_LOGIN = 899999,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_GATE_LOGIN", Value=899998)]
      RES_GATE_LOGIN = 899998,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_GET_ACCOUNTINFO", Value=899997)]
      REQ_GET_ACCOUNTINFO = 899997,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_GET_ACCOUNTINFO", Value=899996)]
      RES_GET_ACCOUNTINFO = 899996,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_GET_GAMEZONEINFO_LIST", Value=899995)]
      REQ_GET_GAMEZONEINFO_LIST = 899995,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_GET_GAMEZONEINFO_LIST", Value=899994)]
      RES_GET_GAMEZONEINFO_LIST = 899994,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_GET_GAMEZONE_DETAIL", Value=899993)]
      REQ_GET_GAMEZONE_DETAIL = 899993,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_GET_GAMEZONE_DETAIL", Value=899992)]
      RES_GET_GAMEZONE_DETAIL = 899992,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_JOIN_LOGIC_GAMEROOM", Value=899991)]
      REQ_JOIN_LOGIC_GAMEROOM = 899991,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_JOIN_LOGIC_GAMEROOM", Value=899990)]
      RES_JOIN_LOGIC_GAMEROOM = 899990,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_QUICK_JOIN_GAMEROOM", Value=899989)]
      REQ_QUICK_JOIN_GAMEROOM = 899989,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_QUICK_JOIN_GAMEROOM", Value=899988)]
      RES_QUICK_JOIN_GAMEROOM = 899988,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_NOTIFY_BROAD_PLAT_MARQUEE", Value=899987)]
      RES_NOTIFY_BROAD_PLAT_MARQUEE = 899987,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_NOTIFY_SELF_DATA_CHANGE", Value=899986)]
      RES_NOTIFY_SELF_DATA_CHANGE = 899986,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_GET_ROOMBRIFE_LIST", Value=899985)]
      REQ_GET_ROOMBRIFE_LIST = 899985,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_GET_ROOMBRIFE_LIST", Value=899984)]
      RES_GET_ROOMBRIFE_LIST = 899984,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_CHECK_IN_MATCH", Value=899983)]
      REQ_CHECK_IN_MATCH = 899983,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_CHECK_IN_MATCH", Value=899982)]
      RES_CHECK_IN_MATCH = 899982,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_OPEN_ROOM_REPLACE", Value=899981)]
      REQ_OPEN_ROOM_REPLACE = 899981,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_OPEN_ROOM_REPLACE", Value=899980)]
      RES_OPEN_ROOM_REPLACE = 899980,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_OPEN_ROOM_REPLACE_RECORD_LIST", Value=899979)]
      REQ_OPEN_ROOM_REPLACE_RECORD_LIST = 899979,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_OPEN_ROOM_REPLACE_RECORD_LIST", Value=899978)]
      RES_OPEN_ROOM_REPLACE_RECORD_LIST = 899978,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_DISSOLUTION_OPEN_ROOM_REPLACE", Value=899977)]
      REQ_DISSOLUTION_OPEN_ROOM_REPLACE = 899977,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_DISSOLUTION_OPEN_ROOM_REPLACE", Value=899976)]
      RES_DISSOLUTION_OPEN_ROOM_REPLACE = 899976,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_GAME_ROOM_LIST", Value=899975)]
      REQ_GAME_ROOM_LIST = 899975,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_GAME_ROOM_LIST", Value=899974)]
      RES_GAME_ROOM_LIST = 899974,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_CLUB_GAME_ROOM_LIST", Value=899973)]
      REQ_CLUB_GAME_ROOM_LIST = 899973,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_CLUB_GAME_ROOM_LIST", Value=899972)]
      RES_CLUB_GAME_ROOM_LIST = 899972,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_CLUB_PIPEI_ROOM", Value=899971)]
      REQ_CLUB_PIPEI_ROOM = 899971,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_CLUB_PIPEI_ROOM", Value=899970)]
      RES_CLUB_PIPEI_ROOM = 899970,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_EXIT_CLUB_PIPEI_ROOM", Value=899969)]
      REQ_EXIT_CLUB_PIPEI_ROOM = 899969,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_EXIT_CLUB_PIPEI_ROOM", Value=899968)]
      RES_EXIT_CLUB_PIPEI_ROOM = 899968,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_CLUB_PIPEI_ROOM_STATUS", Value=899967)]
      REQ_CLUB_PIPEI_ROOM_STATUS = 899967,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_CLUB_PIPEI_ROOM_STATUS", Value=899966)]
      RES_CLUB_PIPEI_ROOM_STATUS = 899966,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_NOTIFY_CLUB_PIPEI_SUC", Value=899965)]
      RES_NOTIFY_CLUB_PIPEI_SUC = 899965,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_NOTIFY_REFRESH_CLUB_GAME_ROOM_LIST", Value=899964)]
      RES_NOTIFY_REFRESH_CLUB_GAME_ROOM_LIST = 899964,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_NOTIFY_REFRESH_CLUB_RED_BOT_NEWS", Value=899963)]
      RES_NOTIFY_REFRESH_CLUB_RED_BOT_NEWS = 899963,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_NOTIFY_CLUB_DISMISS", Value=899962)]
      RES_NOTIFY_CLUB_DISMISS = 899962,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_NOTIFY_CLUB_KICKED_OUT", Value=899961)]
      RES_NOTIFY_CLUB_KICKED_OUT = 899961,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_NOTIFY_CLUB_CHANGE_GAME_TYPE", Value=899960)]
      RES_NOTIFY_CLUB_CHANGE_GAME_TYPE = 899960,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_LOGIC_LOGIN", Value=799999)]
      REQ_LOGIC_LOGIN = 799999,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_LOGIC_LOGIN", Value=799998)]
      RES_LOGIC_LOGIN = 799998,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_CREATE_GAMEROOM", Value=799997)]
      REQ_CREATE_GAMEROOM = 799997,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_CREATE_GAMEROOM", Value=799996)]
      RES_CREATE_GAMEROOM = 799996,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_NOTIFY_GAMEROOM_CREATE", Value=799995)]
      RES_NOTIFY_GAMEROOM_CREATE = 799995,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_JOIN_GAMEROOM", Value=799994)]
      REQ_JOIN_GAMEROOM = 799994,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_JOIN_GAMEROOM", Value=799993)]
      RES_JOIN_GAMEROOM = 799993,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_NOTIFY_SOMEONE_JOIN_GAMEROOM", Value=799992)]
      RES_NOTIFY_SOMEONE_JOIN_GAMEROOM = 799992,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_EXIT_GAMEROOM", Value=799991)]
      REQ_EXIT_GAMEROOM = 799991,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_EXIT_GAMEROOM", Value=799990)]
      RES_EXIT_GAMEROOM = 799990,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_NOTIFY_SOMEONE_EXIT_GAMEROOM", Value=799989)]
      RES_NOTIFY_SOMEONE_EXIT_GAMEROOM = 799989,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_GAME_READY", Value=799988)]
      REQ_GAME_READY = 799988,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_GAME_READY", Value=799987)]
      RES_GAME_READY = 799987,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_DISSOLUTION_GAMEROOM", Value=799983)]
      REQ_DISSOLUTION_GAMEROOM = 799983,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_DISSOLUTION_GAMEROOM", Value=799982)]
      RES_DISSOLUTION_GAMEROOM = 799982,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_NOTIFY_SOMEONE_REQ_DISSOLUTION_GAMEROOM", Value=799981)]
      RES_NOTIFY_SOMEONE_REQ_DISSOLUTION_GAMEROOM = 799981,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_AGREE_DISSOLUTION_GAMEROOM", Value=799980)]
      REQ_AGREE_DISSOLUTION_GAMEROOM = 799980,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_AGREE_DISSOLUTION_GAMEROOM", Value=799979)]
      RES_AGREE_DISSOLUTION_GAMEROOM = 799979,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_NOTIFY_SOMEONE_AGREE_DISSOLUTION_GAMEROOM", Value=799978)]
      RES_NOTIFY_SOMEONE_AGREE_DISSOLUTION_GAMEROOM = 799978,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_NOTIFY_GAMEROOM_DISSOLUTION", Value=799977)]
      RES_NOTIFY_GAMEROOM_DISSOLUTION = 799977,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_NOTIFY_GAMEOVER", Value=799976)]
      RES_NOTIFY_GAMEOVER = 799976,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_GET_ROOM_INFO", Value=799975)]
      REQ_GET_ROOM_INFO = 799975,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_GET_ROOM_INFO", Value=799974)]
      RES_GET_ROOM_INFO = 799974,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_NOTIFY_SOMEONE_GAME_READY", Value=799973)]
      RES_NOTIFY_SOMEONE_GAME_READY = 799973,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_CHANGE_ONLINE_STATUS", Value=799972)]
      REQ_CHANGE_ONLINE_STATUS = 799972,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_CHANGE_ONLINE_STATUS", Value=799971)]
      RES_CHANGE_ONLINE_STATUS = 799971,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_NOTIFY_SOMEONE_CHANGE_ONLINE_STATUS", Value=799970)]
      RES_NOTIFY_SOMEONE_CHANGE_ONLINE_STATUS = 799970,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_NOTIFY_BIG_CALCULATE_PANEL", Value=799969)]
      RES_NOTIFY_BIG_CALCULATE_PANEL = 799969,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_CORRECT_TIMER", Value=799966)]
      REQ_CORRECT_TIMER = 799966,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_CORRECT_TIMER", Value=799965)]
      RES_CORRECT_TIMER = 799965,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_QUICK_CHANGE_ROOM", Value=799964)]
      REQ_QUICK_CHANGE_ROOM = 799964,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_QUICK_CHANGE_ROOM", Value=799963)]
      RES_QUICK_CHANGE_ROOM = 799963,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_NOTIFY_SOMEONE_CHANGE_ROBOT", Value=799962)]
      RES_NOTIFY_SOMEONE_CHANGE_ROBOT = 799962,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_NOTIFY_CHANGE_TO_OLDROOM", Value=799961)]
      RES_NOTIFY_CHANGE_TO_OLDROOM = 799961,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_SIT_DOWN", Value=799960)]
      REQ_SIT_DOWN = 799960,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_SIT_DOWN", Value=799959)]
      RES_SIT_DOWN = 799959,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_NOTIFY_SOMEONE_SIT_DOWN", Value=799958)]
      RES_NOTIFY_SOMEONE_SIT_DOWN = 799958,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_STAND_UP", Value=799957)]
      REQ_STAND_UP = 799957,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_STAND_UP", Value=799956)]
      RES_STAND_UP = 799956,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_NOTIFY_SOMEONE_STAND_UP", Value=799955)]
      RES_NOTIFY_SOMEONE_STAND_UP = 799955,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_NOTIFY_SOMEONE_ENTER_CHARGE", Value=799954)]
      RES_NOTIFY_SOMEONE_ENTER_CHARGE = 799954,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_NOTIFY_ACCOUNTS_CHANGE", Value=799953)]
      RES_NOTIFY_ACCOUNTS_CHANGE = 799953,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_NOTIFY_CHARGE_OVER", Value=799952)]
      RES_NOTIFY_CHARGE_OVER = 799952,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_WATCHER_LIST", Value=799951)]
      REQ_WATCHER_LIST = 799951,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_WATCHER_LIST", Value=799950)]
      RES_WATCHER_LIST = 799950,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_ONCE_MORE", Value=799948)]
      REQ_ONCE_MORE = 799948,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_ONCE_MORE", Value=799949)]
      RES_ONCE_MORE = 799949,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_ONOTIFY_ONCE_MORE", Value=799947)]
      RES_ONOTIFY_ONCE_MORE = 799947,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_LOGIC_SERVER_TIME", Value=799946)]
      REQ_LOGIC_SERVER_TIME = 799946,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_LOGIC_SERVER_TIME", Value=799945)]
      RES_LOGIC_SERVER_TIME = 799945,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_SEAT_DOWN", Value=799799)]
      REQ_SEAT_DOWN = 799799,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_SEAT_DOWN", Value=799798)]
      RES_SEAT_DOWN = 799798,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_BE_WATHER", Value=799797)]
      REQ_BE_WATHER = 799797,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_BE_WATHER", Value=799796)]
      RES_BE_WATHER = 799796,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_NOTIFY_ADD_WATHER", Value=799795)]
      RES_NOTIFY_ADD_WATHER = 799795,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_NOTIFY_REMOVE_WATHER", Value=799794)]
      RES_NOTIFY_REMOVE_WATHER = 799794,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_NOTIFY_DISSOLUTION_CONNECT", Value=999990)]
      RES_NOTIFY_DISSOLUTION_CONNECT = 999990,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_NOTIFY_CHAT_ARRIVE", Value=999991)]
      RES_NOTIFY_CHAT_ARRIVE = 999991,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_CHAT", Value=999992)]
      RES_CHAT = 999992,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_CHAT", Value=999993)]
      REQ_CHAT = 999993,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_NOTIFY_BE_KICK_OUT", Value=999994)]
      RES_NOTIFY_BE_KICK_OUT = 999994,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_EXCEPTION_CATCH", Value=999995)]
      RES_EXCEPTION_CATCH = 999995,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_HEART_BEAT", Value=999996)]
      RES_HEART_BEAT = 999996,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_HEART_BEAT", Value=999997)]
      REQ_HEART_BEAT = 999997,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_CONNECT_CREATE", Value=999998)]
      RES_CONNECT_CREATE = 999998,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_NOTIFY_ALERT", Value=999999)]
      RES_NOTIFY_ALERT = 999999
    }
  
}