//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: MsgDouniu.proto
// Note: requires additional types generated from: MsgLogic.proto
// Note: requires additional types generated from: MsgCode.proto
namespace ProtoNet
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SmallCalculatePanel_8854")]
  public partial class SmallCalculatePanel_8854 : global::ProtoBuf.IExtensible
  {
    public SmallCalculatePanel_8854() {}
    
    private readonly global::System.Collections.Generic.List<ProtoNet.SmallCalController_8854> _smallCalControllers = new global::System.Collections.Generic.List<ProtoNet.SmallCalController_8854>();
    [global::ProtoBuf.ProtoMember(1, Name=@"smallCalControllers", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoNet.SmallCalController_8854> smallCalControllers
    {
      get { return _smallCalControllers; }
    }
  
    private string _bankerUniqueId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"bankerUniqueId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string bankerUniqueId
    {
      get { return _bankerUniqueId; }
      set { _bankerUniqueId = value; }
    }
    private int _bankerPos;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"bankerPos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int bankerPos
    {
      get { return _bankerPos; }
      set { _bankerPos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SmallCalController_8854")]
  public partial class SmallCalController_8854 : global::ProtoBuf.IExtensible
  {
    public SmallCalController_8854() {}
    
    private int _winScore;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"winScore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int winScore
    {
      get { return _winScore; }
      set { _winScore = value; }
    }
    private string _uniqueId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"uniqueId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string uniqueId
    {
      get { return _uniqueId; }
      set { _uniqueId = value; }
    }
    private int _pos;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private int _health;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"health", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int health
    {
      get { return _health; }
      set { _health = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BigCalController_8854")]
  public partial class BigCalController_8854 : global::ProtoBuf.IExtensible
  {
    public BigCalController_8854() {}
    
    private string _headImg;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"headImg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string headImg
    {
      get { return _headImg; }
      set { _headImg = value; }
    }
    private string _nick;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"nick", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string nick
    {
      get { return _nick; }
      set { _nick = value; }
    }
    private string _uniqueId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"uniqueId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string uniqueId
    {
      get { return _uniqueId; }
      set { _uniqueId = value; }
    }
    private int _head;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"head", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int head
    {
      get { return _head; }
      set { _head = value; }
    }
    private int _winScore;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"winScore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int winScore
    {
      get { return _winScore; }
      set { _winScore = value; }
    }
    private int _niuniuCount;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"niuniuCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int niuniuCount
    {
      get { return _niuniuCount; }
      set { _niuniuCount = value; }
    }
    private int _winCount;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"winCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int winCount
    {
      get { return _winCount; }
      set { _winCount = value; }
    }
    private int _loseCount;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"loseCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int loseCount
    {
      get { return _loseCount; }
      set { _loseCount = value; }
    }
    private int _tongshaCount;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"tongshaCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int tongshaCount
    {
      get { return _tongshaCount; }
      set { _tongshaCount = value; }
    }
    private int _tongpeiCount;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"tongpeiCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int tongpeiCount
    {
      get { return _tongpeiCount; }
      set { _tongpeiCount = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BigCalculatePanel_8854")]
  public partial class BigCalculatePanel_8854 : global::ProtoBuf.IExtensible
  {
    public BigCalculatePanel_8854() {}
    
    private readonly global::System.Collections.Generic.List<ProtoNet.BigCalController_8854> _controllers = new global::System.Collections.Generic.List<ProtoNet.BigCalController_8854>();
    [global::ProtoBuf.ProtoMember(1, Name=@"controllers", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoNet.BigCalController_8854> controllers
    {
      get { return _controllers; }
    }
  
    private string _roomerId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roomerId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roomerId
    {
      get { return _roomerId; }
      set { _roomerId = value; }
    }
    private string _roomId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"QiangzhuangOperate_8854")]
  public partial class QiangzhuangOperate_8854 : global::ProtoBuf.IExtensible
  {
    public QiangzhuangOperate_8854() {}
    
    private int _pos;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private string _uniqueId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"uniqueId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string uniqueId
    {
      get { return _uniqueId; }
      set { _uniqueId = value; }
    }
    private int _maxFan;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"maxFan", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int maxFan
    {
      get { return _maxFan; }
      set { _maxFan = value; }
    }
    private int _chooseFan = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"chooseFan", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int chooseFan
    {
      get { return _chooseFan; }
      set { _chooseFan = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"YazhuOperate_8854")]
  public partial class YazhuOperate_8854 : global::ProtoBuf.IExtensible
  {
    public YazhuOperate_8854() {}
    
    private int _pos;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private string _uniqueId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"uniqueId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string uniqueId
    {
      get { return _uniqueId; }
      set { _uniqueId = value; }
    }
    private int _maxFan;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"maxFan", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int maxFan
    {
      get { return _maxFan; }
      set { _maxFan = value; }
    }
    private int _chooseFan = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"chooseFan", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int chooseFan
    {
      get { return _chooseFan; }
      set { _chooseFan = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CardInfo_8854")]
  public partial class CardInfo_8854 : global::ProtoBuf.IExtensible
  {
    public CardInfo_8854() {}
    
    private string _cardId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"cardId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string cardId
    {
      get { return _cardId; }
      set { _cardId = value; }
    }
    private int _cardColor;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"cardColor", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int cardColor
    {
      get { return _cardColor; }
      set { _cardColor = value; }
    }
    private int _cardNum;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"cardNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int cardNum
    {
      get { return _cardNum; }
      set { _cardNum = value; }
    }
    private bool _laizi;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"laizi", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool laizi
    {
      get { return _laizi; }
      set { _laizi = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PosGameInfo_8854")]
  public partial class PosGameInfo_8854 : global::ProtoBuf.IExtensible
  {
    public PosGameInfo_8854() {}
    
    private ProtoNet.PosBrife _posBrife;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"posBrife", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoNet.PosBrife posBrife
    {
      get { return _posBrife; }
      set { _posBrife = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ControllerDispachInfo_8854")]
  public partial class ControllerDispachInfo_8854 : global::ProtoBuf.IExtensible
  {
    public ControllerDispachInfo_8854() {}
    
    private string _uniqueId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uniqueId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string uniqueId
    {
      get { return _uniqueId; }
      set { _uniqueId = value; }
    }
    private int _pos;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoNet.CardInfo_8854> _cardInfos = new global::System.Collections.Generic.List<ProtoNet.CardInfo_8854>();
    [global::ProtoBuf.ProtoMember(3, Name=@"cardInfos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoNet.CardInfo_8854> cardInfos
    {
      get { return _cardInfos; }
    }
  
    private int _type = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private int _multiple = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"multiple", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int multiple
    {
      get { return _multiple; }
      set { _multiple = value; }
    }
    private int _isTuoGuan = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"isTuoGuan", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int isTuoGuan
    {
      get { return _isTuoGuan; }
      set { _isTuoGuan = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DouniuGameRoom_8854")]
  public partial class DouniuGameRoom_8854 : global::ProtoBuf.IExtensible
  {
    public DouniuGameRoom_8854() {}
    
    private ProtoNet.RoomInfo _roomInfo;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoNet.RoomInfo roomInfo
    {
      get { return _roomInfo; }
      set { _roomInfo = value; }
    }
    private int _leftMatchCount;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"leftMatchCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int leftMatchCount
    {
      get { return _leftMatchCount; }
      set { _leftMatchCount = value; }
    }
    private string _bankerUniqueId = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"bankerUniqueId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string bankerUniqueId
    {
      get { return _bankerUniqueId; }
      set { _bankerUniqueId = value; }
    }
    private bool _gameing;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"gameing", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool gameing
    {
      get { return _gameing; }
      set { _gameing = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoNet.PosGameInfo_8854> _posGameInfos = new global::System.Collections.Generic.List<ProtoNet.PosGameInfo_8854>();
    [global::ProtoBuf.ProtoMember(5, Name=@"posGameInfos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoNet.PosGameInfo_8854> posGameInfos
    {
      get { return _posGameInfos; }
    }
  
    private int _model;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"model", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int model
    {
      get { return _model; }
      set { _model = value; }
    }
    private int _fan = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"fan", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int fan
    {
      get { return _fan; }
      set { _fan = value; }
    }
    private int _rubCard = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"rubCard", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int rubCard
    {
      get { return _rubCard; }
      set { _rubCard = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqQiangzhuang_8854")]
  public partial class ReqQiangzhuang_8854 : global::ProtoBuf.IExtensible
  {
    public ReqQiangzhuang_8854() {}
    
    private int _fan;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"fan", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int fan
    {
      get { return _fan; }
      set { _fan = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResQiangzhuang_8854")]
  public partial class ResQiangzhuang_8854 : global::ProtoBuf.IExtensible
  {
    public ResQiangzhuang_8854() {}
    
    private ProtoNet.ResponseResult _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoNet.ResponseResult result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResNotifySomeOneQiangzhuang_8854")]
  public partial class ResNotifySomeOneQiangzhuang_8854 : global::ProtoBuf.IExtensible
  {
    public ResNotifySomeOneQiangzhuang_8854() {}
    
    private string _uniqueId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uniqueId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string uniqueId
    {
      get { return _uniqueId; }
      set { _uniqueId = value; }
    }
    private int _pos;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private int _fan;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"fan", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int fan
    {
      get { return _fan; }
      set { _fan = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LiangPaiOperate_8854")]
  public partial class LiangPaiOperate_8854 : global::ProtoBuf.IExtensible
  {
    public LiangPaiOperate_8854() {}
    
    private string _uniqueId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uniqueId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string uniqueId
    {
      get { return _uniqueId; }
      set { _uniqueId = value; }
    }
    private int _pos;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoNet.CardInfo_8854> _cardInfos = new global::System.Collections.Generic.List<ProtoNet.CardInfo_8854>();
    [global::ProtoBuf.ProtoMember(3, Name=@"cardInfos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoNet.CardInfo_8854> cardInfos
    {
      get { return _cardInfos; }
    }
  
    private int _type = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private int _multiple = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"multiple", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int multiple
    {
      get { return _multiple; }
      set { _multiple = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResNotifyGameStart_8854")]
  public partial class ResNotifyGameStart_8854 : global::ProtoBuf.IExtensible
  {
    public ResNotifyGameStart_8854() {}
    
    private ProtoNet.DouniuGameRoom_8854 _douniuGameRoom;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"douniuGameRoom", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoNet.DouniuGameRoom_8854 douniuGameRoom
    {
      get { return _douniuGameRoom; }
      set { _douniuGameRoom = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResNotifyDispachCard_8854")]
  public partial class ResNotifyDispachCard_8854 : global::ProtoBuf.IExtensible
  {
    public ResNotifyDispachCard_8854() {}
    
    private readonly global::System.Collections.Generic.List<ProtoNet.ControllerDispachInfo_8854> _recoverControllerInfos = new global::System.Collections.Generic.List<ProtoNet.ControllerDispachInfo_8854>();
    [global::ProtoBuf.ProtoMember(1, Name=@"recoverControllerInfos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoNet.ControllerDispachInfo_8854> recoverControllerInfos
    {
      get { return _recoverControllerInfos; }
    }
  
    private int _operateType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"operateType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int operateType
    {
      get { return _operateType; }
      set { _operateType = value; }
    }
    private int _fanMax = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"fanMax", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int fanMax
    {
      get { return _fanMax; }
      set { _fanMax = value; }
    }
    private int _qiangzhuangTimer = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"qiangzhuangTimer", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int qiangzhuangTimer
    {
      get { return _qiangzhuangTimer; }
      set { _qiangzhuangTimer = value; }
    }
    private int _maxYazhuFan = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"maxYazhuFan", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int maxYazhuFan
    {
      get { return _maxYazhuFan; }
      set { _maxYazhuFan = value; }
    }
    private int _yazhuTimer = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"yazhuTimer", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int yazhuTimer
    {
      get { return _yazhuTimer; }
      set { _yazhuTimer = value; }
    }
    private string _bankerId = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"bankerId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string bankerId
    {
      get { return _bankerId; }
      set { _bankerId = value; }
    }
    private int _bankerPos = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"bankerPos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int bankerPos
    {
      get { return _bankerPos; }
      set { _bankerPos = value; }
    }
    private string _canyu = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"canyu", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string canyu
    {
      get { return _canyu; }
      set { _canyu = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqYazhu_8854")]
  public partial class ReqYazhu_8854 : global::ProtoBuf.IExtensible
  {
    public ReqYazhu_8854() {}
    
    private int _yazhuFan;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"yazhuFan", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int yazhuFan
    {
      get { return _yazhuFan; }
      set { _yazhuFan = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResYazhu_8854")]
  public partial class ResYazhu_8854 : global::ProtoBuf.IExtensible
  {
    public ResYazhu_8854() {}
    
    private ProtoNet.ResponseResult _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoNet.ResponseResult result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResNotifySomeOneYazhu_8854")]
  public partial class ResNotifySomeOneYazhu_8854 : global::ProtoBuf.IExtensible
  {
    public ResNotifySomeOneYazhu_8854() {}
    
    private string _uniqueId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uniqueId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string uniqueId
    {
      get { return _uniqueId; }
      set { _uniqueId = value; }
    }
    private int _pos;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private int _yazhuFan;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"yazhuFan", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int yazhuFan
    {
      get { return _yazhuFan; }
      set { _yazhuFan = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResNotifyDispachLeftCard_8854")]
  public partial class ResNotifyDispachLeftCard_8854 : global::ProtoBuf.IExtensible
  {
    public ResNotifyDispachLeftCard_8854() {}
    
    private readonly global::System.Collections.Generic.List<ProtoNet.CardInfo_8854> _cardInfos = new global::System.Collections.Generic.List<ProtoNet.CardInfo_8854>();
    [global::ProtoBuf.ProtoMember(1, Name=@"cardInfos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoNet.CardInfo_8854> cardInfos
    {
      get { return _cardInfos; }
    }
  
    private int _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private int _multiple;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"multiple", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int multiple
    {
      get { return _multiple; }
      set { _multiple = value; }
    }
    private int _timer;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"timer", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int timer
    {
      get { return _timer; }
      set { _timer = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqLiangPai_8854")]
  public partial class ReqLiangPai_8854 : global::ProtoBuf.IExtensible
  {
    public ReqLiangPai_8854() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResLiangPai_8854")]
  public partial class ResLiangPai_8854 : global::ProtoBuf.IExtensible
  {
    public ResLiangPai_8854() {}
    
    private ProtoNet.ResponseResult _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoNet.ResponseResult result
    {
      get { return _result; }
      set { _result = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoNet.CardInfo_8854> _cardInfos = new global::System.Collections.Generic.List<ProtoNet.CardInfo_8854>();
    [global::ProtoBuf.ProtoMember(2, Name=@"cardInfos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoNet.CardInfo_8854> cardInfos
    {
      get { return _cardInfos; }
    }
  
    private int _type = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private int _multiple = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"multiple", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int multiple
    {
      get { return _multiple; }
      set { _multiple = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResNotifySomeOneLiangPai_8854")]
  public partial class ResNotifySomeOneLiangPai_8854 : global::ProtoBuf.IExtensible
  {
    public ResNotifySomeOneLiangPai_8854() {}
    
    private string _uniqueId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uniqueId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string uniqueId
    {
      get { return _uniqueId; }
      set { _uniqueId = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoNet.CardInfo_8854> _cardInfos = new global::System.Collections.Generic.List<ProtoNet.CardInfo_8854>();
    [global::ProtoBuf.ProtoMember(2, Name=@"cardInfos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoNet.CardInfo_8854> cardInfos
    {
      get { return _cardInfos; }
    }
  
    private int _type;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private int _multiple;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"multiple", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int multiple
    {
      get { return _multiple; }
      set { _multiple = value; }
    }
    private int _pos;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqSmallCalculatePanel_8854")]
  public partial class ReqSmallCalculatePanel_8854 : global::ProtoBuf.IExtensible
  {
    public ReqSmallCalculatePanel_8854() {}
    
    private string _roomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private int _times;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int times
    {
      get { return _times; }
      set { _times = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResSmallCalculatePanel_8854")]
  public partial class ResSmallCalculatePanel_8854 : global::ProtoBuf.IExtensible
  {
    public ResSmallCalculatePanel_8854() {}
    
    private ProtoNet.ResponseResult _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoNet.ResponseResult result
    {
      get { return _result; }
      set { _result = value; }
    }
    private ProtoNet.SmallCalculatePanel_8854 _smallCalculatePanel = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"smallCalculatePanel", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoNet.SmallCalculatePanel_8854 smallCalculatePanel
    {
      get { return _smallCalculatePanel; }
      set { _smallCalculatePanel = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqBigCalculatePanel_8854")]
  public partial class ReqBigCalculatePanel_8854 : global::ProtoBuf.IExtensible
  {
    public ReqBigCalculatePanel_8854() {}
    
    private string _roomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private bool _containSmall;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"containSmall", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool containSmall
    {
      get { return _containSmall; }
      set { _containSmall = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResBigCalculatePanel_8854")]
  public partial class ResBigCalculatePanel_8854 : global::ProtoBuf.IExtensible
  {
    public ResBigCalculatePanel_8854() {}
    
    private ProtoNet.ResponseResult _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoNet.ResponseResult result
    {
      get { return _result; }
      set { _result = value; }
    }
    private ProtoNet.BigCalculatePanel_8854 _bigCalculatePanel = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"bigCalculatePanel", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoNet.BigCalculatePanel_8854 bigCalculatePanel
    {
      get { return _bigCalculatePanel; }
      set { _bigCalculatePanel = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqRecoverGameSceen_8854")]
  public partial class ReqRecoverGameSceen_8854 : global::ProtoBuf.IExtensible
  {
    public ReqRecoverGameSceen_8854() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResRecoverGameSceen_8854")]
  public partial class ResRecoverGameSceen_8854 : global::ProtoBuf.IExtensible
  {
    public ResRecoverGameSceen_8854() {}
    
    private ProtoNet.ResponseResult _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoNet.ResponseResult result
    {
      get { return _result; }
      set { _result = value; }
    }
    private int _gameId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"gameId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gameId
    {
      get { return _gameId; }
      set { _gameId = value; }
    }
    private int _roomStatus = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"roomStatus", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int roomStatus
    {
      get { return _roomStatus; }
      set { _roomStatus = value; }
    }
    private ProtoNet.RoomInfo _roomInfo = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"roomInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoNet.RoomInfo roomInfo
    {
      get { return _roomInfo; }
      set { _roomInfo = value; }
    }
    private ProtoNet.DouniuGameRoom_8854 _douniuGameRoom = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"douniuGameRoom", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoNet.DouniuGameRoom_8854 douniuGameRoom
    {
      get { return _douniuGameRoom; }
      set { _douniuGameRoom = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoNet.QiangzhuangOperate_8854> _qiangzhaungOperates = new global::System.Collections.Generic.List<ProtoNet.QiangzhuangOperate_8854>();
    [global::ProtoBuf.ProtoMember(6, Name=@"qiangzhaungOperates", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoNet.QiangzhuangOperate_8854> qiangzhaungOperates
    {
      get { return _qiangzhaungOperates; }
    }
  
    private readonly global::System.Collections.Generic.List<ProtoNet.YazhuOperate_8854> _yazhuOperates = new global::System.Collections.Generic.List<ProtoNet.YazhuOperate_8854>();
    [global::ProtoBuf.ProtoMember(7, Name=@"yazhuOperates", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoNet.YazhuOperate_8854> yazhuOperates
    {
      get { return _yazhuOperates; }
    }
  
    private readonly global::System.Collections.Generic.List<ProtoNet.LiangPaiOperate_8854> _liangPaiOperates = new global::System.Collections.Generic.List<ProtoNet.LiangPaiOperate_8854>();
    [global::ProtoBuf.ProtoMember(8, Name=@"liangPaiOperates", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoNet.LiangPaiOperate_8854> liangPaiOperates
    {
      get { return _liangPaiOperates; }
    }
  
    private readonly global::System.Collections.Generic.List<ProtoNet.ControllerDispachInfo_8854> _recoverControllerInfos = new global::System.Collections.Generic.List<ProtoNet.ControllerDispachInfo_8854>();
    [global::ProtoBuf.ProtoMember(9, Name=@"recoverControllerInfos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoNet.ControllerDispachInfo_8854> recoverControllerInfos
    {
      get { return _recoverControllerInfos; }
    }
  
    private int _selfQiangzhuangMaxFan = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"selfQiangzhuangMaxFan", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int selfQiangzhuangMaxFan
    {
      get { return _selfQiangzhuangMaxFan; }
      set { _selfQiangzhuangMaxFan = value; }
    }
    private int _selfYazhuMaxFan = default(int);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"selfYazhuMaxFan", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int selfYazhuMaxFan
    {
      get { return _selfYazhuMaxFan; }
      set { _selfYazhuMaxFan = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResTuoGuan_8854")]
  public partial class ResTuoGuan_8854 : global::ProtoBuf.IExtensible
  {
    public ResTuoGuan_8854() {}
    
    private int _isTuoGuan = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"isTuoGuan", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int isTuoGuan
    {
      get { return _isTuoGuan; }
      set { _isTuoGuan = value; }
    }
    private string _uniqueId = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"uniqueId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string uniqueId
    {
      get { return _uniqueId; }
      set { _uniqueId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"DouniuCode")]
    public enum DouniuCode
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_QIANGZHUANG_8854", Value=709998)]
      REQ_QIANGZHUANG_8854 = 709998,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_QIANGZHUANG_8854", Value=709997)]
      RES_QIANGZHUANG_8854 = 709997,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_NOTIFY_SOMEONE_QIANGZHUANG_8854", Value=709996)]
      RES_NOTIFY_SOMEONE_QIANGZHUANG_8854 = 709996,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_NOTIFY_GAME_START_8854", Value=709995)]
      RES_NOTIFY_GAME_START_8854 = 709995,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_NOTIFY_DISPACH_CARD_8854", Value=709994)]
      RES_NOTIFY_DISPACH_CARD_8854 = 709994,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_YAZHU_8854", Value=709992)]
      REQ_YAZHU_8854 = 709992,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_YAZHU_8854", Value=709991)]
      RES_YAZHU_8854 = 709991,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_NOTIFY_SOMEONE_YAZHU_8854", Value=709990)]
      RES_NOTIFY_SOMEONE_YAZHU_8854 = 709990,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_NOTIFY_DISPACH_LEFT_CARD_8854", Value=709989)]
      RES_NOTIFY_DISPACH_LEFT_CARD_8854 = 709989,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_LIANG_PAI_8854", Value=709988)]
      REQ_LIANG_PAI_8854 = 709988,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_LIANG_PAI_8854", Value=709987)]
      RES_LIANG_PAI_8854 = 709987,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_NOTIFY_SOMEONE_LIANG_PAI_8854", Value=709986)]
      RES_NOTIFY_SOMEONE_LIANG_PAI_8854 = 709986,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_SMALL_CALCULATE_PANEL_8854", Value=709985)]
      REQ_SMALL_CALCULATE_PANEL_8854 = 709985,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_SMALL_CALCULATE_PANEL_8854", Value=709984)]
      RES_SMALL_CALCULATE_PANEL_8854 = 709984,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_BIG_CALCULATE_PANEL_8854", Value=709983)]
      REQ_BIG_CALCULATE_PANEL_8854 = 709983,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_BIG_CALCULATE_PANEL_8854", Value=709982)]
      RES_BIG_CALCULATE_PANEL_8854 = 709982,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_RECOVER_GAMESCEEN_8854", Value=709981)]
      REQ_RECOVER_GAMESCEEN_8854 = 709981,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_RECOVER_GAMESCEEN_8854", Value=709980)]
      RES_RECOVER_GAMESCEEN_8854 = 709980,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_TUOGUAN_8854", Value=709979)]
      RES_TUOGUAN_8854 = 709979
    }
  
}