//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: MsgGate.proto
// Note: requires additional types generated from: MsgCode.proto
namespace ProtoNet
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AccountInfo")]
  public partial class AccountInfo : global::ProtoBuf.IExtensible
  {
    public AccountInfo() {}
    
    private string _name = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private string _nick = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"nick", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string nick
    {
      get { return _nick; }
      set { _nick = value; }
    }
    private int _uid = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private int _sex = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int sex
    {
      get { return _sex; }
      set { _sex = value; }
    }
    private string _phone = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"phone", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string phone
    {
      get { return _phone; }
      set { _phone = value; }
    }
    private string _email = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"email", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string email
    {
      get { return _email; }
      set { _email = value; }
    }
    private int _head = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"head", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int head
    {
      get { return _head; }
      set { _head = value; }
    }
    private string _headUrl = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"headUrl", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string headUrl
    {
      get { return _headUrl; }
      set { _headUrl = value; }
    }
    private int _lv = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"lv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int lv
    {
      get { return _lv; }
      set { _lv = value; }
    }
    private int _vip = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"vip", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int vip
    {
      get { return _vip; }
      set { _vip = value; }
    }
    private string _ipaddress = "";
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"ipaddress", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ipaddress
    {
      get { return _ipaddress; }
      set { _ipaddress = value; }
    }
    private string _address = "";
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"address", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string address
    {
      get { return _address; }
      set { _address = value; }
    }
    private int _inviter = default(int);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"inviter", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int inviter
    {
      get { return _inviter; }
      set { _inviter = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoNet.PlayerAccount> _counts = new global::System.Collections.Generic.List<ProtoNet.PlayerAccount>();
    [global::ProtoBuf.ProtoMember(14, Name=@"counts", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoNet.PlayerAccount> counts
    {
      get { return _counts; }
    }
  
    private ProtoNet.LastGameInfo _lastGameInfo = null;
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"lastGameInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoNet.LastGameInfo lastGameInfo
    {
      get { return _lastGameInfo; }
      set { _lastGameInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LastGameInfo")]
  public partial class LastGameInfo : global::ProtoBuf.IExtensible
  {
    public LastGameInfo() {}
    
    private int _gameId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"gameId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gameId
    {
      get { return _gameId; }
      set { _gameId = value; }
    }
    private ProtoNet.LastGameInfoDetail _detail = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"detail", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoNet.LastGameInfoDetail detail
    {
      get { return _detail; }
      set { _detail = value; }
    }
    private ProtoNet.ServerInfoIpsSafeDetail _gate = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"gate", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoNet.ServerInfoIpsSafeDetail gate
    {
      get { return _gate; }
      set { _gate = value; }
    }
    private ProtoNet.ServerInfoIpsSafeDetail _logic = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"logic", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoNet.ServerInfoIpsSafeDetail logic
    {
      get { return _logic; }
      set { _logic = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LastGameInfoDetail")]
  public partial class LastGameInfoDetail : global::ProtoBuf.IExtensible
  {
    public LastGameInfoDetail() {}
    
    private int _type = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private string _roomId = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private int _status = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int status
    {
      get { return _status; }
      set { _status = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameZoneInfo")]
  public partial class GameZoneInfo : global::ProtoBuf.IExtensible
  {
    public GameZoneInfo() {}
    
    private int _gameId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"gameId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gameId
    {
      get { return _gameId; }
      set { _gameId = value; }
    }
    private bool _isOpen = default(bool);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"isOpen", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isOpen
    {
      get { return _isOpen; }
      set { _isOpen = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ServerInfoIpsSafeDetail")]
  public partial class ServerInfoIpsSafeDetail : global::ProtoBuf.IExtensible
  {
    public ServerInfoIpsSafeDetail() {}
    
    private int _serverId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"serverId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int serverId
    {
      get { return _serverId; }
      set { _serverId = value; }
    }
    private string _serverName = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"serverName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string serverName
    {
      get { return _serverName; }
      set { _serverName = value; }
    }
    private int _playerNum = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"playerNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int playerNum
    {
      get { return _playerNum; }
      set { _playerNum = value; }
    }
    private bool _isOpen = default(bool);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"isOpen", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isOpen
    {
      get { return _isOpen; }
      set { _isOpen = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoNet.SafeIpAndPortDetail> _safeIpAndPortDetails = new global::System.Collections.Generic.List<ProtoNet.SafeIpAndPortDetail>();
    [global::ProtoBuf.ProtoMember(5, Name=@"safeIpAndPortDetails", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoNet.SafeIpAndPortDetail> safeIpAndPortDetails
    {
      get { return _safeIpAndPortDetails; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SafeIpAndPortDetail")]
  public partial class SafeIpAndPortDetail : global::ProtoBuf.IExtensible
  {
    public SafeIpAndPortDetail() {}
    
    private string _safeIp = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"safeIp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string safeIp
    {
      get { return _safeIp; }
      set { _safeIp = value; }
    }
    private string _safePort = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"safePort", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string safePort
    {
      get { return _safePort; }
      set { _safePort = value; }
    }
    private string _evironment = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"evironment", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string evironment
    {
      get { return _evironment; }
      set { _evironment = value; }
    }
    private string _safeHttpPort = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"safeHttpPort", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string safeHttpPort
    {
      get { return _safeHttpPort; }
      set { _safeHttpPort = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GoldRoomServerInfos")]
  public partial class GoldRoomServerInfos : global::ProtoBuf.IExtensible
  {
    public GoldRoomServerInfos() {}
    
    private string _roomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private string _roomName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roomName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roomName
    {
      get { return _roomName; }
      set { _roomName = value; }
    }
    private string _roomerUniqueId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"roomerUniqueId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roomerUniqueId
    {
      get { return _roomerUniqueId; }
      set { _roomerUniqueId = value; }
    }
    private string _roomerNickName;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"roomerNickName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roomerNickName
    {
      get { return _roomerNickName; }
      set { _roomerNickName = value; }
    }
    private string _roomerHeadImg;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"roomerHeadImg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roomerHeadImg
    {
      get { return _roomerHeadImg; }
      set { _roomerHeadImg = value; }
    }
    private int _roomerHeadType;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"roomerHeadType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int roomerHeadType
    {
      get { return _roomerHeadType; }
      set { _roomerHeadType = value; }
    }
    private int _roomType;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"roomType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int roomType
    {
      get { return _roomType; }
      set { _roomType = value; }
    }
    private int _gameId;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"gameId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int gameId
    {
      get { return _gameId; }
      set { _gameId = value; }
    }
    private int _timesType;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"timesType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int timesType
    {
      get { return _timesType; }
      set { _timesType = value; }
    }
    private ProtoNet.ServerInfoIpsSafeDetail _serverInfo;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"serverInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoNet.ServerInfoIpsSafeDetail serverInfo
    {
      get { return _serverInfo; }
      set { _serverInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OpenRoomReplaceRecordInfo")]
  public partial class OpenRoomReplaceRecordInfo : global::ProtoBuf.IExtensible
  {
    public OpenRoomReplaceRecordInfo() {}
    
    private string _roomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private string _roomerUniqueId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roomerUniqueId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roomerUniqueId
    {
      get { return _roomerUniqueId; }
      set { _roomerUniqueId = value; }
    }
    private string _roomerNickName;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"roomerNickName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roomerNickName
    {
      get { return _roomerNickName; }
      set { _roomerNickName = value; }
    }
    private long _createTime;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"createTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long createTime
    {
      get { return _createTime; }
      set { _createTime = value; }
    }
    private int _gameId;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"gameId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int gameId
    {
      get { return _gameId; }
      set { _gameId = value; }
    }
    private int _roomType;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"roomType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int roomType
    {
      get { return _roomType; }
      set { _roomType = value; }
    }
    private int _timesType;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"timesType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int timesType
    {
      get { return _timesType; }
      set { _timesType = value; }
    }
    private int _totalTime;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"totalTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int totalTime
    {
      get { return _totalTime; }
      set { _totalTime = value; }
    }
    private ProtoNet.ServerInfoIpsSafeDetail _serverInfo;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"serverInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoNet.ServerInfoIpsSafeDetail serverInfo
    {
      get { return _serverInfo; }
      set { _serverInfo = value; }
    }
    private int _totalNum;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"totalNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int totalNum
    {
      get { return _totalNum; }
      set { _totalNum = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoNet.ReplaceRecordOver> _replaceRecordOver = new global::System.Collections.Generic.List<ProtoNet.ReplaceRecordOver>();
    [global::ProtoBuf.ProtoMember(11, Name=@"replaceRecordOver", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoNet.ReplaceRecordOver> replaceRecordOver
    {
      get { return _replaceRecordOver; }
    }
  
    private string _jsonParam;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"jsonParam", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string jsonParam
    {
      get { return _jsonParam; }
      set { _jsonParam = value; }
    }
    private int _status;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int status
    {
      get { return _status; }
      set { _status = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReplaceRecordOver")]
  public partial class ReplaceRecordOver : global::ProtoBuf.IExtensible
  {
    public ReplaceRecordOver() {}
    
    private string _uniqueId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uniqueId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string uniqueId
    {
      get { return _uniqueId; }
      set { _uniqueId = value; }
    }
    private string _nick;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"nick", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string nick
    {
      get { return _nick; }
      set { _nick = value; }
    }
    private string _headImg;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"headImg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string headImg
    {
      get { return _headImg; }
      set { _headImg = value; }
    }
    private int _head;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"head", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int head
    {
      get { return _head; }
      set { _head = value; }
    }
    private double _score = default(double);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double score
    {
      get { return _score; }
      set { _score = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TimesInfo")]
  public partial class TimesInfo : global::ProtoBuf.IExtensible
  {
    public TimesInfo() {}
    
    private int _timesType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"timesType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int timesType
    {
      get { return _timesType; }
      set { _timesType = value; }
    }
    private string _timesName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"timesName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string timesName
    {
      get { return _timesName; }
      set { _timesName = value; }
    }
    private double _minNeed;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"minNeed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double minNeed
    {
      get { return _minNeed; }
      set { _minNeed = value; }
    }
    private double _yazhu;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"yazhu", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double yazhu
    {
      get { return _yazhu; }
      set { _yazhu = value; }
    }
    private int _atype;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"atype", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int atype
    {
      get { return _atype; }
      set { _atype = value; }
    }
    private int _roomType;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"roomType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int roomType
    {
      get { return _roomType; }
      set { _roomType = value; }
    }
    private string _extendStr = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"extendStr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string extendStr
    {
      get { return _extendStr; }
      set { _extendStr = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqGateLogin")]
  public partial class ReqGateLogin : global::ProtoBuf.IExtensible
  {
    public ReqGateLogin() {}
    
    private int _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private string _ticket;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"ticket", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ticket
    {
      get { return _ticket; }
      set { _ticket = value; }
    }
    private string _evironment;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"evironment", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string evironment
    {
      get { return _evironment; }
      set { _evironment = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResGateLogin")]
  public partial class ResGateLogin : global::ProtoBuf.IExtensible
  {
    public ResGateLogin() {}
    
    private ProtoNet.ResponseResult _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoNet.ResponseResult result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqGetAccountInfo")]
  public partial class ReqGetAccountInfo : global::ProtoBuf.IExtensible
  {
    public ReqGetAccountInfo() {}
    
    private int _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResGetAccountInfo")]
  public partial class ResGetAccountInfo : global::ProtoBuf.IExtensible
  {
    public ResGetAccountInfo() {}
    
    private ProtoNet.ResponseResult _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoNet.ResponseResult result
    {
      get { return _result; }
      set { _result = value; }
    }
    private ProtoNet.AccountInfo _accountInfo = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"accountInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoNet.AccountInfo accountInfo
    {
      get { return _accountInfo; }
      set { _accountInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqGetGameZoneInfoList")]
  public partial class ReqGetGameZoneInfoList : global::ProtoBuf.IExtensible
  {
    public ReqGetGameZoneInfoList() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResGetGameZoneInfoList")]
  public partial class ResGetGameZoneInfoList : global::ProtoBuf.IExtensible
  {
    public ResGetGameZoneInfoList() {}
    
    private ProtoNet.ResponseResult _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoNet.ResponseResult result
    {
      get { return _result; }
      set { _result = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoNet.GameZoneInfo> _gameZoneInfos = new global::System.Collections.Generic.List<ProtoNet.GameZoneInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"gameZoneInfos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoNet.GameZoneInfo> gameZoneInfos
    {
      get { return _gameZoneInfos; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqGetGameZoneDetail")]
  public partial class ReqGetGameZoneDetail : global::ProtoBuf.IExtensible
  {
    public ReqGetGameZoneDetail() {}
    
    private int _gameId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"gameId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int gameId
    {
      get { return _gameId; }
      set { _gameId = value; }
    }
    private int _roomType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roomType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int roomType
    {
      get { return _roomType; }
      set { _roomType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResGetGameZoneDetail")]
  public partial class ResGetGameZoneDetail : global::ProtoBuf.IExtensible
  {
    public ResGetGameZoneDetail() {}
    
    private ProtoNet.ResponseResult _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoNet.ResponseResult result
    {
      get { return _result; }
      set { _result = value; }
    }
    private int _gameId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"gameId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gameId
    {
      get { return _gameId; }
      set { _gameId = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoNet.ServerInfoIpsSafeDetail> _logicDetails = new global::System.Collections.Generic.List<ProtoNet.ServerInfoIpsSafeDetail>();
    [global::ProtoBuf.ProtoMember(3, Name=@"logicDetails", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoNet.ServerInfoIpsSafeDetail> logicDetails
    {
      get { return _logicDetails; }
    }
  
    private readonly global::System.Collections.Generic.List<ProtoNet.TimesInfo> _timesInfos = new global::System.Collections.Generic.List<ProtoNet.TimesInfo>();
    [global::ProtoBuf.ProtoMember(4, Name=@"timesInfos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoNet.TimesInfo> timesInfos
    {
      get { return _timesInfos; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqJoinLogicGameRoom")]
  public partial class ReqJoinLogicGameRoom : global::ProtoBuf.IExtensible
  {
    public ReqJoinLogicGameRoom() {}
    
    private string _roomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResJoinLogicGameRoom")]
  public partial class ResJoinLogicGameRoom : global::ProtoBuf.IExtensible
  {
    public ResJoinLogicGameRoom() {}
    
    private ProtoNet.ResponseResult _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoNet.ResponseResult result
    {
      get { return _result; }
      set { _result = value; }
    }
    private ProtoNet.ServerInfoIpsSafeDetail _bestServerInfo = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"bestServerInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoNet.ServerInfoIpsSafeDetail bestServerInfo
    {
      get { return _bestServerInfo; }
      set { _bestServerInfo = value; }
    }
    private int _gameId = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"gameId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gameId
    {
      get { return _gameId; }
      set { _gameId = value; }
    }
    private int _roomType = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"roomType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int roomType
    {
      get { return _roomType; }
      set { _roomType = value; }
    }
    private int _timesType = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"timesType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int timesType
    {
      get { return _timesType; }
      set { _timesType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqQuickJoinGameRoom")]
  public partial class ReqQuickJoinGameRoom : global::ProtoBuf.IExtensible
  {
    public ReqQuickJoinGameRoom() {}
    
    private int _gameId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"gameId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int gameId
    {
      get { return _gameId; }
      set { _gameId = value; }
    }
    private int _roomType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roomType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int roomType
    {
      get { return _roomType; }
      set { _roomType = value; }
    }
    private int _timesType;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"timesType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int timesType
    {
      get { return _timesType; }
      set { _timesType = value; }
    }
    private string _pipeiParam = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"pipeiParam", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string pipeiParam
    {
      get { return _pipeiParam; }
      set { _pipeiParam = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResQuickJoinGameRoom")]
  public partial class ResQuickJoinGameRoom : global::ProtoBuf.IExtensible
  {
    public ResQuickJoinGameRoom() {}
    
    private ProtoNet.ResponseResult _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoNet.ResponseResult result
    {
      get { return _result; }
      set { _result = value; }
    }
    private int _operate = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"operate", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int operate
    {
      get { return _operate; }
      set { _operate = value; }
    }
    private int _roomType = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"roomType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int roomType
    {
      get { return _roomType; }
      set { _roomType = value; }
    }
    private ProtoNet.ServerInfoIpsSafeDetail _bestServerInfo = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"bestServerInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoNet.ServerInfoIpsSafeDetail bestServerInfo
    {
      get { return _bestServerInfo; }
      set { _bestServerInfo = value; }
    }
    private string _roomId = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoNet.ServerInfoIpsSafeDetail> _logicDetails = new global::System.Collections.Generic.List<ProtoNet.ServerInfoIpsSafeDetail>();
    [global::ProtoBuf.ProtoMember(6, Name=@"logicDetails", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoNet.ServerInfoIpsSafeDetail> logicDetails
    {
      get { return _logicDetails; }
    }
  
    private int _gameId = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"gameId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gameId
    {
      get { return _gameId; }
      set { _gameId = value; }
    }
    private int _timesType = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"timesType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int timesType
    {
      get { return _timesType; }
      set { _timesType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResNotifyBroadPlatMarquee")]
  public partial class ResNotifyBroadPlatMarquee : global::ProtoBuf.IExtensible
  {
    public ResNotifyBroadPlatMarquee() {}
    
    private int _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private string _msg;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string msg
    {
      get { return _msg; }
      set { _msg = value; }
    }
    private int _count;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int count
    {
      get { return _count; }
      set { _count = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResNotifySelfDataChange")]
  public partial class ResNotifySelfDataChange : global::ProtoBuf.IExtensible
  {
    public ResNotifySelfDataChange() {}
    
    private ProtoNet.AccountInfo _accountInfo;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"accountInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoNet.AccountInfo accountInfo
    {
      get { return _accountInfo; }
      set { _accountInfo = value; }
    }
    private int _charge = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"charge", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int charge
    {
      get { return _charge; }
      set { _charge = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqGetRoomBrifeList")]
  public partial class ReqGetRoomBrifeList : global::ProtoBuf.IExtensible
  {
    public ReqGetRoomBrifeList() {}
    
    private int _gameId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"gameId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int gameId
    {
      get { return _gameId; }
      set { _gameId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResGetRoomBrifeList")]
  public partial class ResGetRoomBrifeList : global::ProtoBuf.IExtensible
  {
    public ResGetRoomBrifeList() {}
    
    private ProtoNet.ResponseResult _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoNet.ResponseResult result
    {
      get { return _result; }
      set { _result = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoNet.GoldRoomServerInfos> _goldRoomServerInfos = new global::System.Collections.Generic.List<ProtoNet.GoldRoomServerInfos>();
    [global::ProtoBuf.ProtoMember(2, Name=@"goldRoomServerInfos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoNet.GoldRoomServerInfos> goldRoomServerInfos
    {
      get { return _goldRoomServerInfos; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqCheckInMatch")]
  public partial class ReqCheckInMatch : global::ProtoBuf.IExtensible
  {
    public ReqCheckInMatch() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResCheckInMatch")]
  public partial class ResCheckInMatch : global::ProtoBuf.IExtensible
  {
    public ResCheckInMatch() {}
    
    private ProtoNet.ResponseResult _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoNet.ResponseResult result
    {
      get { return _result; }
      set { _result = value; }
    }
    private int _inMatch = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"inMatch", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int inMatch
    {
      get { return _inMatch; }
      set { _inMatch = value; }
    }
    private string _randId = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"randId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string randId
    {
      get { return _randId; }
      set { _randId = value; }
    }
    private int _matchConfigId = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"matchConfigId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int matchConfigId
    {
      get { return _matchConfigId; }
      set { _matchConfigId = value; }
    }
    private int _gameId = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"gameId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gameId
    {
      get { return _gameId; }
      set { _gameId = value; }
    }
    private int _selfRank = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"selfRank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int selfRank
    {
      get { return _selfRank; }
      set { _selfRank = value; }
    }
    private int _from = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"from", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int from
    {
      get { return _from; }
      set { _from = value; }
    }
    private int _to = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"to", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int to
    {
      get { return _to; }
      set { _to = value; }
    }
    private int _taotai = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"taotai", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int taotai
    {
      get { return _taotai; }
      set { _taotai = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqOpenRoomReplace")]
  public partial class ReqOpenRoomReplace : global::ProtoBuf.IExtensible
  {
    public ReqOpenRoomReplace() {}
    
    private int _roomType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int roomType
    {
      get { return _roomType; }
      set { _roomType = value; }
    }
    private int _times;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int times
    {
      get { return _times; }
      set { _times = value; }
    }
    private string _paramString = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"paramString", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string paramString
    {
      get { return _paramString; }
      set { _paramString = value; }
    }
    private int _timesType;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"timesType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int timesType
    {
      get { return _timesType; }
      set { _timesType = value; }
    }
    private int _halfWayJoin = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"halfWayJoin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int halfWayJoin
    {
      get { return _halfWayJoin; }
      set { _halfWayJoin = value; }
    }
    private int _maxPlayerNum = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"maxPlayerNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int maxPlayerNum
    {
      get { return _maxPlayerNum; }
      set { _maxPlayerNum = value; }
    }
    private double _yazhu = default(double);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"yazhu", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double yazhu
    {
      get { return _yazhu; }
      set { _yazhu = value; }
    }
    private int _gameId;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"gameId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int gameId
    {
      get { return _gameId; }
      set { _gameId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResOpenRoomReplace")]
  public partial class ResOpenRoomReplace : global::ProtoBuf.IExtensible
  {
    public ResOpenRoomReplace() {}
    
    private ProtoNet.ResponseResult _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoNet.ResponseResult result
    {
      get { return _result; }
      set { _result = value; }
    }
    private string _roomId = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private int _roomType = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"roomType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int roomType
    {
      get { return _roomType; }
      set { _roomType = value; }
    }
    private int _times = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int times
    {
      get { return _times; }
      set { _times = value; }
    }
    private string _paramString = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"paramString", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string paramString
    {
      get { return _paramString; }
      set { _paramString = value; }
    }
    private int _timesType = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"timesType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int timesType
    {
      get { return _timesType; }
      set { _timesType = value; }
    }
    private int _halfWayJoin = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"halfWayJoin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int halfWayJoin
    {
      get { return _halfWayJoin; }
      set { _halfWayJoin = value; }
    }
    private int _maxPlayerNum = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"maxPlayerNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int maxPlayerNum
    {
      get { return _maxPlayerNum; }
      set { _maxPlayerNum = value; }
    }
    private double _yazhu = default(double);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"yazhu", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double yazhu
    {
      get { return _yazhu; }
      set { _yazhu = value; }
    }
    private int _gameId = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"gameId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gameId
    {
      get { return _gameId; }
      set { _gameId = value; }
    }
    private ProtoNet.ServerInfoIpsSafeDetail _serverInfo = null;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"serverInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoNet.ServerInfoIpsSafeDetail serverInfo
    {
      get { return _serverInfo; }
      set { _serverInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqOpenRoomReplaceRecordList")]
  public partial class ReqOpenRoomReplaceRecordList : global::ProtoBuf.IExtensible
  {
    public ReqOpenRoomReplaceRecordList() {}
    
    private int _status;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int status
    {
      get { return _status; }
      set { _status = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResOpenRoomReplaceRecord_List")]
  public partial class ResOpenRoomReplaceRecord_List : global::ProtoBuf.IExtensible
  {
    public ResOpenRoomReplaceRecord_List() {}
    
    private ProtoNet.ResponseResult _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoNet.ResponseResult result
    {
      get { return _result; }
      set { _result = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoNet.OpenRoomReplaceRecordInfo> _infos = new global::System.Collections.Generic.List<ProtoNet.OpenRoomReplaceRecordInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"infos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoNet.OpenRoomReplaceRecordInfo> infos
    {
      get { return _infos; }
    }
  
    private int _daikaifangRecordNum = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"daikaifangRecordNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int daikaifangRecordNum
    {
      get { return _daikaifangRecordNum; }
      set { _daikaifangRecordNum = value; }
    }
    private int _status = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int status
    {
      get { return _status; }
      set { _status = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqDissolutionOpenRoomReplace")]
  public partial class ReqDissolutionOpenRoomReplace : global::ProtoBuf.IExtensible
  {
    public ReqDissolutionOpenRoomReplace() {}
    
    private string _roomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResDissolutionOpenRoomReplace")]
  public partial class ResDissolutionOpenRoomReplace : global::ProtoBuf.IExtensible
  {
    public ResDissolutionOpenRoomReplace() {}
    
    private ProtoNet.ResponseResult _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoNet.ResponseResult result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqGameRoomList")]
  public partial class ReqGameRoomList : global::ProtoBuf.IExtensible
  {
    public ReqGameRoomList() {}
    
    private int _gameId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"gameId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int gameId
    {
      get { return _gameId; }
      set { _gameId = value; }
    }
    private int _timesType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"timesType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int timesType
    {
      get { return _timesType; }
      set { _timesType = value; }
    }
    private int _fangkaJinbi;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"fangkaJinbi", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int fangkaJinbi
    {
      get { return _fangkaJinbi; }
      set { _fangkaJinbi = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResGameRoomList")]
  public partial class ResGameRoomList : global::ProtoBuf.IExtensible
  {
    public ResGameRoomList() {}
    
    private ProtoNet.ResponseResult _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoNet.ResponseResult result
    {
      get { return _result; }
      set { _result = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoNet.GameRoomList> _list = new global::System.Collections.Generic.List<ProtoNet.GameRoomList>();
    [global::ProtoBuf.ProtoMember(2, Name=@"list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoNet.GameRoomList> list
    {
      get { return _list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameRoomList")]
  public partial class GameRoomList : global::ProtoBuf.IExtensible
  {
    public GameRoomList() {}
    
    private string _roomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private string _paramString;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"paramString", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string paramString
    {
      get { return _paramString; }
      set { _paramString = value; }
    }
    private double _yazhu;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"yazhu", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double yazhu
    {
      get { return _yazhu; }
      set { _yazhu = value; }
    }
    private int _halfWayJoin;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"halfWayJoin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int halfWayJoin
    {
      get { return _halfWayJoin; }
      set { _halfWayJoin = value; }
    }
    private int _maxPlayerNum;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"maxPlayerNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int maxPlayerNum
    {
      get { return _maxPlayerNum; }
      set { _maxPlayerNum = value; }
    }
    private int _fangkaJinbi;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"fangkaJinbi", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int fangkaJinbi
    {
      get { return _fangkaJinbi; }
      set { _fangkaJinbi = value; }
    }
    private double _minNeed;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"minNeed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double minNeed
    {
      get { return _minNeed; }
      set { _minNeed = value; }
    }
    private string _pipeiParam;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"pipeiParam", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string pipeiParam
    {
      get { return _pipeiParam; }
      set { _pipeiParam = value; }
    }
    private ProtoNet.ServerInfoIpsSafeDetail _serverInfo;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"serverInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoNet.ServerInfoIpsSafeDetail serverInfo
    {
      get { return _serverInfo; }
      set { _serverInfo = value; }
    }
    private int _gameId;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"gameId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int gameId
    {
      get { return _gameId; }
      set { _gameId = value; }
    }
    private int _currentPlayerNum;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"currentPlayerNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int currentPlayerNum
    {
      get { return _currentPlayerNum; }
      set { _currentPlayerNum = value; }
    }
    private int _roomStatus;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"roomStatus", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int roomStatus
    {
      get { return _roomStatus; }
      set { _roomStatus = value; }
    }
    private int _currentWatchPlayerNum;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"currentWatchPlayerNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int currentWatchPlayerNum
    {
      get { return _currentWatchPlayerNum; }
      set { _currentWatchPlayerNum = value; }
    }
    private int _roomType = default(int);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"roomType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int roomType
    {
      get { return _roomType; }
      set { _roomType = value; }
    }
    private int _timesType = default(int);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"timesType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int timesType
    {
      get { return _timesType; }
      set { _timesType = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoNet.RoomRoleInfo> _roomRoleInfo = new global::System.Collections.Generic.List<ProtoNet.RoomRoleInfo>();
    [global::ProtoBuf.ProtoMember(16, Name=@"roomRoleInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoNet.RoomRoleInfo> roomRoleInfo
    {
      get { return _roomRoleInfo; }
    }
  
    private string _tableNum = "";
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"tableNum", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string tableNum
    {
      get { return _tableNum; }
      set { _tableNum = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqClubGameRoomList")]
  public partial class ReqClubGameRoomList : global::ProtoBuf.IExtensible
  {
    public ReqClubGameRoomList() {}
    
    private int _roomType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int roomType
    {
      get { return _roomType; }
      set { _roomType = value; }
    }
    private int _gameId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"gameId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int gameId
    {
      get { return _gameId; }
      set { _gameId = value; }
    }
    private string _clubId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"clubId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string clubId
    {
      get { return _clubId; }
      set { _clubId = value; }
    }
    private string _clubPipeiParam;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"clubPipeiParam", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string clubPipeiParam
    {
      get { return _clubPipeiParam; }
      set { _clubPipeiParam = value; }
    }
    private string _clubGameTypeId = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"clubGameTypeId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string clubGameTypeId
    {
      get { return _clubGameTypeId; }
      set { _clubGameTypeId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResClubGameRoomList")]
  public partial class ResClubGameRoomList : global::ProtoBuf.IExtensible
  {
    public ResClubGameRoomList() {}
    
    private ProtoNet.ResponseResult _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoNet.ResponseResult result
    {
      get { return _result; }
      set { _result = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoNet.ClubGameRoomList> _list = new global::System.Collections.Generic.List<ProtoNet.ClubGameRoomList>();
    [global::ProtoBuf.ProtoMember(2, Name=@"list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoNet.ClubGameRoomList> list
    {
      get { return _list; }
    }
  
    private int _clubCurNum = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"clubCurNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int clubCurNum
    {
      get { return _clubCurNum; }
      set { _clubCurNum = value; }
    }
    private int _clubTotalNumLimit = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"clubTotalNumLimit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int clubTotalNumLimit
    {
      get { return _clubTotalNumLimit; }
      set { _clubTotalNumLimit = value; }
    }
    private int _onlineTotal = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"onlineTotal", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int onlineTotal
    {
      get { return _onlineTotal; }
      set { _onlineTotal = value; }
    }
    private string _clubId = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"clubId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string clubId
    {
      get { return _clubId; }
      set { _clubId = value; }
    }
    private int _totalCard = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"totalCard", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int totalCard
    {
      get { return _totalCard; }
      set { _totalCard = value; }
    }
    private string _intro = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"intro", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string intro
    {
      get { return _intro; }
      set { _intro = value; }
    }
    private int _playingNum = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"playingNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int playingNum
    {
      get { return _playingNum; }
      set { _playingNum = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ClubGameRoomList")]
  public partial class ClubGameRoomList : global::ProtoBuf.IExtensible
  {
    public ClubGameRoomList() {}
    
    private string _roomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private string _paramString;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"paramString", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string paramString
    {
      get { return _paramString; }
      set { _paramString = value; }
    }
    private double _yazhu;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"yazhu", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double yazhu
    {
      get { return _yazhu; }
      set { _yazhu = value; }
    }
    private int _halfWayJoin;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"halfWayJoin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int halfWayJoin
    {
      get { return _halfWayJoin; }
      set { _halfWayJoin = value; }
    }
    private int _maxPlayerNum;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"maxPlayerNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int maxPlayerNum
    {
      get { return _maxPlayerNum; }
      set { _maxPlayerNum = value; }
    }
    private int _fangkaJinbi;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"fangkaJinbi", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int fangkaJinbi
    {
      get { return _fangkaJinbi; }
      set { _fangkaJinbi = value; }
    }
    private double _minNeed;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"minNeed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double minNeed
    {
      get { return _minNeed; }
      set { _minNeed = value; }
    }
    private string _pipeiParam;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"pipeiParam", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string pipeiParam
    {
      get { return _pipeiParam; }
      set { _pipeiParam = value; }
    }
    private ProtoNet.ServerInfoIpsSafeDetail _serverInfo;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"serverInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoNet.ServerInfoIpsSafeDetail serverInfo
    {
      get { return _serverInfo; }
      set { _serverInfo = value; }
    }
    private int _gameId;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"gameId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int gameId
    {
      get { return _gameId; }
      set { _gameId = value; }
    }
    private int _currentPlayerNum;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"currentPlayerNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int currentPlayerNum
    {
      get { return _currentPlayerNum; }
      set { _currentPlayerNum = value; }
    }
    private int _roomStatus;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"roomStatus", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int roomStatus
    {
      get { return _roomStatus; }
      set { _roomStatus = value; }
    }
    private int _currentWatchPlayerNum;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"currentWatchPlayerNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int currentWatchPlayerNum
    {
      get { return _currentWatchPlayerNum; }
      set { _currentWatchPlayerNum = value; }
    }
    private int _roomType;
    [global::ProtoBuf.ProtoMember(14, IsRequired = true, Name=@"roomType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int roomType
    {
      get { return _roomType; }
      set { _roomType = value; }
    }
    private int _timesType;
    [global::ProtoBuf.ProtoMember(15, IsRequired = true, Name=@"timesType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int timesType
    {
      get { return _timesType; }
      set { _timesType = value; }
    }
    private string _tableNum = "";
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"tableNum", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string tableNum
    {
      get { return _tableNum; }
      set { _tableNum = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoNet.RoomRoleInfo> _roomRoleInfo = new global::System.Collections.Generic.List<ProtoNet.RoomRoleInfo>();
    [global::ProtoBuf.ProtoMember(17, Name=@"roomRoleInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoNet.RoomRoleInfo> roomRoleInfo
    {
      get { return _roomRoleInfo; }
    }
  
    private string _roomerUniqueId = "";
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"roomerUniqueId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string roomerUniqueId
    {
      get { return _roomerUniqueId; }
      set { _roomerUniqueId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoomRoleInfo")]
  public partial class RoomRoleInfo : global::ProtoBuf.IExtensible
  {
    public RoomRoleInfo() {}
    
    private string _uniqueId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uniqueId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string uniqueId
    {
      get { return _uniqueId; }
      set { _uniqueId = value; }
    }
    private string _nickName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"nickName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string nickName
    {
      get { return _nickName; }
      set { _nickName = value; }
    }
    private string _headImg;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"headImg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string headImg
    {
      get { return _headImg; }
      set { _headImg = value; }
    }
    private int _head;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"head", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int head
    {
      get { return _head; }
      set { _head = value; }
    }
    private int _pos;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqClubPipeiRoom")]
  public partial class ReqClubPipeiRoom : global::ProtoBuf.IExtensible
  {
    public ReqClubPipeiRoom() {}
    
    private int _roomType = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"roomType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int roomType
    {
      get { return _roomType; }
      set { _roomType = value; }
    }
    private int _times = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int times
    {
      get { return _times; }
      set { _times = value; }
    }
    private string _paramString = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"paramString", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string paramString
    {
      get { return _paramString; }
      set { _paramString = value; }
    }
    private int _timesType = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"timesType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int timesType
    {
      get { return _timesType; }
      set { _timesType = value; }
    }
    private int _halfWayJoin = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"halfWayJoin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int halfWayJoin
    {
      get { return _halfWayJoin; }
      set { _halfWayJoin = value; }
    }
    private int _maxPlayerNum = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"maxPlayerNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int maxPlayerNum
    {
      get { return _maxPlayerNum; }
      set { _maxPlayerNum = value; }
    }
    private double _yazhu = default(double);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"yazhu", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double yazhu
    {
      get { return _yazhu; }
      set { _yazhu = value; }
    }
    private int _gameId = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"gameId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gameId
    {
      get { return _gameId; }
      set { _gameId = value; }
    }
    private int _clubId = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"clubId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int clubId
    {
      get { return _clubId; }
      set { _clubId = value; }
    }
    private int _playerId = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private int _payType = default(int);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"payType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int payType
    {
      get { return _payType; }
      set { _payType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResClubPipeiRoom")]
  public partial class ResClubPipeiRoom : global::ProtoBuf.IExtensible
  {
    public ResClubPipeiRoom() {}
    
    private ProtoNet.ResponseResult _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoNet.ResponseResult result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqExitClubPipeiRoom")]
  public partial class ReqExitClubPipeiRoom : global::ProtoBuf.IExtensible
  {
    public ReqExitClubPipeiRoom() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResExitClubPipeiRoom")]
  public partial class ResExitClubPipeiRoom : global::ProtoBuf.IExtensible
  {
    public ResExitClubPipeiRoom() {}
    
    private ProtoNet.ResponseResult _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoNet.ResponseResult result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqClubPipeiRoomStatus")]
  public partial class ReqClubPipeiRoomStatus : global::ProtoBuf.IExtensible
  {
    public ReqClubPipeiRoomStatus() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResClubPipeiRoomStatus")]
  public partial class ResClubPipeiRoomStatus : global::ProtoBuf.IExtensible
  {
    public ResClubPipeiRoomStatus() {}
    
    private ProtoNet.ResponseResult _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoNet.ResponseResult result
    {
      get { return _result; }
      set { _result = value; }
    }
    private int _gameId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"gameId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gameId
    {
      get { return _gameId; }
      set { _gameId = value; }
    }
    private int _clubId = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"clubId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int clubId
    {
      get { return _clubId; }
      set { _clubId = value; }
    }
    private int _times = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int times
    {
      get { return _times; }
      set { _times = value; }
    }
    private string _paramString = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"paramString", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string paramString
    {
      get { return _paramString; }
      set { _paramString = value; }
    }
    private int _maxPlayerNum = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"maxPlayerNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int maxPlayerNum
    {
      get { return _maxPlayerNum; }
      set { _maxPlayerNum = value; }
    }
    private int _matchPlayerNum = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"matchPlayerNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int matchPlayerNum
    {
      get { return _matchPlayerNum; }
      set { _matchPlayerNum = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResNotifyClubPipeiSuc")]
  public partial class ResNotifyClubPipeiSuc : global::ProtoBuf.IExtensible
  {
    public ResNotifyClubPipeiSuc() {}
    
    private string _clubId = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"clubId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string clubId
    {
      get { return _clubId; }
      set { _clubId = value; }
    }
    private string _roomId = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private int _roomType = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"roomType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int roomType
    {
      get { return _roomType; }
      set { _roomType = value; }
    }
    private int _times = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int times
    {
      get { return _times; }
      set { _times = value; }
    }
    private string _paramString = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"paramString", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string paramString
    {
      get { return _paramString; }
      set { _paramString = value; }
    }
    private int _timesType = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"timesType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int timesType
    {
      get { return _timesType; }
      set { _timesType = value; }
    }
    private int _halfWayJoin = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"halfWayJoin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int halfWayJoin
    {
      get { return _halfWayJoin; }
      set { _halfWayJoin = value; }
    }
    private int _maxPlayerNum = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"maxPlayerNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int maxPlayerNum
    {
      get { return _maxPlayerNum; }
      set { _maxPlayerNum = value; }
    }
    private double _yazhu = default(double);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"yazhu", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double yazhu
    {
      get { return _yazhu; }
      set { _yazhu = value; }
    }
    private int _gameId = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"gameId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gameId
    {
      get { return _gameId; }
      set { _gameId = value; }
    }
    private ProtoNet.ServerInfoIpsSafeDetail _serverInfo = null;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"serverInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoNet.ServerInfoIpsSafeDetail serverInfo
    {
      get { return _serverInfo; }
      set { _serverInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResNotifyRefreshClubGameRoomList")]
  public partial class ResNotifyRefreshClubGameRoomList : global::ProtoBuf.IExtensible
  {
    public ResNotifyRefreshClubGameRoomList() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResNotifyRefreshClubRedBotNews")]
  public partial class ResNotifyRefreshClubRedBotNews : global::ProtoBuf.IExtensible
  {
    public ResNotifyRefreshClubRedBotNews() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResNotifyClubDismiss")]
  public partial class ResNotifyClubDismiss : global::ProtoBuf.IExtensible
  {
    public ResNotifyClubDismiss() {}
    
    private string _clubId = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"clubId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string clubId
    {
      get { return _clubId; }
      set { _clubId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResNotifyClubKickedOut")]
  public partial class ResNotifyClubKickedOut : global::ProtoBuf.IExtensible
  {
    public ResNotifyClubKickedOut() {}
    
    private string _clubId = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"clubId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string clubId
    {
      get { return _clubId; }
      set { _clubId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResNotifyClubChangeGameType")]
  public partial class ResNotifyClubChangeGameType : global::ProtoBuf.IExtensible
  {
    public ResNotifyClubChangeGameType() {}
    
    private string _clubId = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"clubId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string clubId
    {
      get { return _clubId; }
      set { _clubId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}