//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: MsgLogicWather.proto
// Note: requires additional types generated from: MsgCode.proto
// Note: requires additional types generated from: MsgGate.proto
// Note: requires additional types generated from: MsgLogic.proto
namespace ProtoNet
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqSeatDown")]
  public partial class ReqSeatDown : global::ProtoBuf.IExtensible
  {
    public ReqSeatDown() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResSeatDown")]
  public partial class ResSeatDown : global::ProtoBuf.IExtensible
  {
    public ResSeatDown() {}
    
    private ProtoNet.ResponseResult _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoNet.ResponseResult result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqBeWather")]
  public partial class ReqBeWather : global::ProtoBuf.IExtensible
  {
    public ReqBeWather() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResBeWather")]
  public partial class ResBeWather : global::ProtoBuf.IExtensible
  {
    public ResBeWather() {}
    
    private ProtoNet.ResponseResult _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoNet.ResponseResult result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResNotifyAddWather")]
  public partial class ResNotifyAddWather : global::ProtoBuf.IExtensible
  {
    public ResNotifyAddWather() {}
    
    private ProtoNet.SdkController _sdkController;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"sdkController", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoNet.SdkController sdkController
    {
      get { return _sdkController; }
      set { _sdkController = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResNotifyRemoveWather")]
  public partial class ResNotifyRemoveWather : global::ProtoBuf.IExtensible
  {
    public ResNotifyRemoveWather() {}
    
    private ProtoNet.SdkController _sdkController;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"sdkController", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoNet.SdkController sdkController
    {
      get { return _sdkController; }
      set { _sdkController = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}