//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: MsgLogic.proto
// Note: requires additional types generated from: MsgCode.proto
// Note: requires additional types generated from: MsgGate.proto
namespace ProtoNet
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SdkController")]
  public partial class SdkController : global::ProtoBuf.IExtensible
  {
    public SdkController() {}
    
    private string _uniqueId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uniqueId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string uniqueId
    {
      get { return _uniqueId; }
      set { _uniqueId = value; }
    }
    private string _nickName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"nickName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string nickName
    {
      get { return _nickName; }
      set { _nickName = value; }
    }
    private string _headImg;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"headImg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string headImg
    {
      get { return _headImg; }
      set { _headImg = value; }
    }
    private string _ip;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"ip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ip
    {
      get { return _ip; }
      set { _ip = value; }
    }
    private int _headType;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"headType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int headType
    {
      get { return _headType; }
      set { _headType = value; }
    }
    private double _health;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"health", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double health
    {
      get { return _health; }
      set { _health = value; }
    }
    private int _sex;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int sex
    {
      get { return _sex; }
      set { _sex = value; }
    }
    private int _selfRank = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"selfRank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int selfRank
    {
      get { return _selfRank; }
      set { _selfRank = value; }
    }
    private int _robot = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"robot", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int robot
    {
      get { return _robot; }
      set { _robot = value; }
    }
    private int _watcher = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"watcher", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int watcher
    {
      get { return _watcher; }
      set { _watcher = value; }
    }
    private int _lv = default(int);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"lv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int lv
    {
      get { return _lv; }
      set { _lv = value; }
    }
    private string _extendStr = "";
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"extendStr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string extendStr
    {
      get { return _extendStr; }
      set { _extendStr = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PosBrife")]
  public partial class PosBrife : global::ProtoBuf.IExtensible
  {
    public PosBrife() {}
    
    private int _pos;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private string _controllerUniqueId = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"controllerUniqueId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string controllerUniqueId
    {
      get { return _controllerUniqueId; }
      set { _controllerUniqueId = value; }
    }
    private int _online = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"online", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int online
    {
      get { return _online; }
      set { _online = value; }
    }
    private int _ready = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"ready", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ready
    {
      get { return _ready; }
      set { _ready = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoomInfo")]
  public partial class RoomInfo : global::ProtoBuf.IExtensible
  {
    public RoomInfo() {}
    
    private string _roomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private string _roomName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roomName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roomName
    {
      get { return _roomName; }
      set { _roomName = value; }
    }
    private string _roomerUniqueId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"roomerUniqueId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roomerUniqueId
    {
      get { return _roomerUniqueId; }
      set { _roomerUniqueId = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoNet.SdkController> _controllers = new global::System.Collections.Generic.List<ProtoNet.SdkController>();
    [global::ProtoBuf.ProtoMember(4, Name=@"controllers", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoNet.SdkController> controllers
    {
      get { return _controllers; }
    }
  
    private string _extendStr = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"extendStr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string extendStr
    {
      get { return _extendStr; }
      set { _extendStr = value; }
    }
    private int _roomStatus;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"roomStatus", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int roomStatus
    {
      get { return _roomStatus; }
      set { _roomStatus = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoNet.PosBrife> _posBrifes = new global::System.Collections.Generic.List<ProtoNet.PosBrife>();
    [global::ProtoBuf.ProtoMember(7, Name=@"posBrifes", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoNet.PosBrife> posBrifes
    {
      get { return _posBrifes; }
    }
  
    private int _leftMatchCount;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"leftMatchCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int leftMatchCount
    {
      get { return _leftMatchCount; }
      set { _leftMatchCount = value; }
    }
    private int _totalCount;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"totalCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int totalCount
    {
      get { return _totalCount; }
      set { _totalCount = value; }
    }
    private ProtoNet.DissolutionStatus _dissolutionStatus;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"dissolutionStatus", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoNet.DissolutionStatus dissolutionStatus
    {
      get { return _dissolutionStatus; }
      set { _dissolutionStatus = value; }
    }
    private int _maxPlayerNum;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"maxPlayerNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int maxPlayerNum
    {
      get { return _maxPlayerNum; }
      set { _maxPlayerNum = value; }
    }
    private int _currentPlayerNum;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"currentPlayerNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int currentPlayerNum
    {
      get { return _currentPlayerNum; }
      set { _currentPlayerNum = value; }
    }
    private long _readyTimer = default(long);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"readyTimer", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long readyTimer
    {
      get { return _readyTimer; }
      set { _readyTimer = value; }
    }
    private int _gameId = default(int);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"gameId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gameId
    {
      get { return _gameId; }
      set { _gameId = value; }
    }
    private int _roomType = default(int);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"roomType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int roomType
    {
      get { return _roomType; }
      set { _roomType = value; }
    }
    private int _timesType = default(int);
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"timesType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int timesType
    {
      get { return _timesType; }
      set { _timesType = value; }
    }
    private double _yazhu = default(double);
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"yazhu", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double yazhu
    {
      get { return _yazhu; }
      set { _yazhu = value; }
    }
    private int _watting = default(int);
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"watting", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int watting
    {
      get { return _watting; }
      set { _watting = value; }
    }
    private int _from = default(int);
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"from", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int from
    {
      get { return _from; }
      set { _from = value; }
    }
    private int _to = default(int);
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"to", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int to
    {
      get { return _to; }
      set { _to = value; }
    }
    private string _serverExtend = "";
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"serverExtend", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string serverExtend
    {
      get { return _serverExtend; }
      set { _serverExtend = value; }
    }
    private int _fangkaJinbi = default(int);
    [global::ProtoBuf.ProtoMember(22, IsRequired = false, Name=@"fangkaJinbi", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int fangkaJinbi
    {
      get { return _fangkaJinbi; }
      set { _fangkaJinbi = value; }
    }
    private string _chargeList = "";
    [global::ProtoBuf.ProtoMember(23, IsRequired = false, Name=@"chargeList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string chargeList
    {
      get { return _chargeList; }
      set { _chargeList = value; }
    }
    private string _ext = "";
    [global::ProtoBuf.ProtoMember(24, IsRequired = false, Name=@"ext", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ext
    {
      get { return _ext; }
      set { _ext = value; }
    }
    private string _clubId = "";
    [global::ProtoBuf.ProtoMember(25, IsRequired = false, Name=@"clubId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string clubId
    {
      get { return _clubId; }
      set { _clubId = value; }
    }
    private string _tableNum = "";
    [global::ProtoBuf.ProtoMember(26, IsRequired = false, Name=@"tableNum", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string tableNum
    {
      get { return _tableNum; }
      set { _tableNum = value; }
    }
    private string _clubGameTypeId = "";
    [global::ProtoBuf.ProtoMember(27, IsRequired = false, Name=@"clubGameTypeId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string clubGameTypeId
    {
      get { return _clubGameTypeId; }
      set { _clubGameTypeId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DissolutionStatus")]
  public partial class DissolutionStatus : global::ProtoBuf.IExtensible
  {
    public DissolutionStatus() {}
    
    private int _dissolutionStatus;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"dissolutionStatus", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int dissolutionStatus
    {
      get { return _dissolutionStatus; }
      set { _dissolutionStatus = value; }
    }
    private string _reqUniqueId = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"reqUniqueId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string reqUniqueId
    {
      get { return _reqUniqueId; }
      set { _reqUniqueId = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoNet.DissolutionStatusDetail> _details = new global::System.Collections.Generic.List<ProtoNet.DissolutionStatusDetail>();
    [global::ProtoBuf.ProtoMember(3, Name=@"details", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoNet.DissolutionStatusDetail> details
    {
      get { return _details; }
    }
  
    private long _leftTimer = default(long);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"leftTimer", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long leftTimer
    {
      get { return _leftTimer; }
      set { _leftTimer = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DissolutionStatusDetail")]
  public partial class DissolutionStatusDetail : global::ProtoBuf.IExtensible
  {
    public DissolutionStatusDetail() {}
    
    private string _roomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private string _controllerUniqueId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"controllerUniqueId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string controllerUniqueId
    {
      get { return _controllerUniqueId; }
      set { _controllerUniqueId = value; }
    }
    private int _agree;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"agree", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int agree
    {
      get { return _agree; }
      set { _agree = value; }
    }
    private int _pos;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqLogicLogin")]
  public partial class ReqLogicLogin : global::ProtoBuf.IExtensible
  {
    public ReqLogicLogin() {}
    
    private string _account;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string account
    {
      get { return _account; }
      set { _account = value; }
    }
    private string _ticket;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"ticket", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ticket
    {
      get { return _ticket; }
      set { _ticket = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResLogicLogin")]
  public partial class ResLogicLogin : global::ProtoBuf.IExtensible
  {
    public ResLogicLogin() {}
    
    private ProtoNet.ResponseResult _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoNet.ResponseResult result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqCreateGameRoom")]
  public partial class ReqCreateGameRoom : global::ProtoBuf.IExtensible
  {
    public ReqCreateGameRoom() {}
    
    private int _roomType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int roomType
    {
      get { return _roomType; }
      set { _roomType = value; }
    }
    private int _times;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int times
    {
      get { return _times; }
      set { _times = value; }
    }
    private string _paramString = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"paramString", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string paramString
    {
      get { return _paramString; }
      set { _paramString = value; }
    }
    private int _timesType;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"timesType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int timesType
    {
      get { return _timesType; }
      set { _timesType = value; }
    }
    private int _payType = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"payType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int payType
    {
      get { return _payType; }
      set { _payType = value; }
    }
    private int _halfWayJoin = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"halfWayJoin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int halfWayJoin
    {
      get { return _halfWayJoin; }
      set { _halfWayJoin = value; }
    }
    private int _maxPlayerNum = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"maxPlayerNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int maxPlayerNum
    {
      get { return _maxPlayerNum; }
      set { _maxPlayerNum = value; }
    }
    private double _yazhu = default(double);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"yazhu", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double yazhu
    {
      get { return _yazhu; }
      set { _yazhu = value; }
    }
    private int _fangkaJinbi = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"fangkaJinbi", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int fangkaJinbi
    {
      get { return _fangkaJinbi; }
      set { _fangkaJinbi = value; }
    }
    private double _minNeed = default(double);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"minNeed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double minNeed
    {
      get { return _minNeed; }
      set { _minNeed = value; }
    }
    private string _pipeiParam = "";
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"pipeiParam", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string pipeiParam
    {
      get { return _pipeiParam; }
      set { _pipeiParam = value; }
    }
    private string _clubId = "";
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"clubId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string clubId
    {
      get { return _clubId; }
      set { _clubId = value; }
    }
    private string _clubTableNum = "";
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"clubTableNum", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string clubTableNum
    {
      get { return _clubTableNum; }
      set { _clubTableNum = value; }
    }
    private string _clubGameTypeId = "";
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"clubGameTypeId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string clubGameTypeId
    {
      get { return _clubGameTypeId; }
      set { _clubGameTypeId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResCreateGameRoom")]
  public partial class ResCreateGameRoom : global::ProtoBuf.IExtensible
  {
    public ResCreateGameRoom() {}
    
    private ProtoNet.ResponseResult _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoNet.ResponseResult result
    {
      get { return _result; }
      set { _result = value; }
    }
    private long _readyTimer = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"readyTimer", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long readyTimer
    {
      get { return _readyTimer; }
      set { _readyTimer = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResNotifyGameRoomCreate")]
  public partial class ResNotifyGameRoomCreate : global::ProtoBuf.IExtensible
  {
    public ResNotifyGameRoomCreate() {}
    
    private string _roomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqJoinGameRoom")]
  public partial class ReqJoinGameRoom : global::ProtoBuf.IExtensible
  {
    public ReqJoinGameRoom() {}
    
    private string _roomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResJoinGameRoom")]
  public partial class ResJoinGameRoom : global::ProtoBuf.IExtensible
  {
    public ResJoinGameRoom() {}
    
    private ProtoNet.ResponseResult _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoNet.ResponseResult result
    {
      get { return _result; }
      set { _result = value; }
    }
    private ProtoNet.RoomInfo _roomInfo = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"roomInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoNet.RoomInfo roomInfo
    {
      get { return _roomInfo; }
      set { _roomInfo = value; }
    }
    private long _readyTimer = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"readyTimer", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long readyTimer
    {
      get { return _readyTimer; }
      set { _readyTimer = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResNotifySomeOneJoinGameRoom")]
  public partial class ResNotifySomeOneJoinGameRoom : global::ProtoBuf.IExtensible
  {
    public ResNotifySomeOneJoinGameRoom() {}
    
    private string _roomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private ProtoNet.SdkController _controller;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"controller", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoNet.SdkController controller
    {
      get { return _controller; }
      set { _controller = value; }
    }
    private ProtoNet.PosBrife _posBrife;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"posBrife", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoNet.PosBrife posBrife
    {
      get { return _posBrife; }
      set { _posBrife = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqExitGameRoom")]
  public partial class ReqExitGameRoom : global::ProtoBuf.IExtensible
  {
    public ReqExitGameRoom() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResExitGameRoom")]
  public partial class ResExitGameRoom : global::ProtoBuf.IExtensible
  {
    public ResExitGameRoom() {}
    
    private ProtoNet.ResponseResult _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoNet.ResponseResult result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResNotifySomeOneExitGameRoom")]
  public partial class ResNotifySomeOneExitGameRoom : global::ProtoBuf.IExtensible
  {
    public ResNotifySomeOneExitGameRoom() {}
    
    private string _roomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private ProtoNet.SdkController _controller;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"controller", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoNet.SdkController controller
    {
      get { return _controller; }
      set { _controller = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqGameReady")]
  public partial class ReqGameReady : global::ProtoBuf.IExtensible
  {
    public ReqGameReady() {}
    
    private bool _ready;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ready", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool ready
    {
      get { return _ready; }
      set { _ready = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResGameReady")]
  public partial class ResGameReady : global::ProtoBuf.IExtensible
  {
    public ResGameReady() {}
    
    private ProtoNet.ResponseResult _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoNet.ResponseResult result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqDissolutionGameRoom")]
  public partial class ReqDissolutionGameRoom : global::ProtoBuf.IExtensible
  {
    public ReqDissolutionGameRoom() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResDissolutionGameRoom")]
  public partial class ResDissolutionGameRoom : global::ProtoBuf.IExtensible
  {
    public ResDissolutionGameRoom() {}
    
    private ProtoNet.ResponseResult _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoNet.ResponseResult result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResNotifySomeOneReqDissolutionGameRoom")]
  public partial class ResNotifySomeOneReqDissolutionGameRoom : global::ProtoBuf.IExtensible
  {
    public ResNotifySomeOneReqDissolutionGameRoom() {}
    
    private string _roomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private ProtoNet.SdkController _controller;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"controller", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoNet.SdkController controller
    {
      get { return _controller; }
      set { _controller = value; }
    }
    private ProtoNet.PosBrife _posBrife;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"posBrife", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoNet.PosBrife posBrife
    {
      get { return _posBrife; }
      set { _posBrife = value; }
    }
    private long _timer;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"timer", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long timer
    {
      get { return _timer; }
      set { _timer = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqAgreeDissolutionGameRoom")]
  public partial class ReqAgreeDissolutionGameRoom : global::ProtoBuf.IExtensible
  {
    public ReqAgreeDissolutionGameRoom() {}
    
    private bool _agree;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"agree", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool agree
    {
      get { return _agree; }
      set { _agree = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResAgreeDissolutionGameRoom")]
  public partial class ResAgreeDissolutionGameRoom : global::ProtoBuf.IExtensible
  {
    public ResAgreeDissolutionGameRoom() {}
    
    private ProtoNet.ResponseResult _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoNet.ResponseResult result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResNotifySomeOneAggreeDissolutionGameRoom")]
  public partial class ResNotifySomeOneAggreeDissolutionGameRoom : global::ProtoBuf.IExtensible
  {
    public ResNotifySomeOneAggreeDissolutionGameRoom() {}
    
    private string _roomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private ProtoNet.SdkController _controller;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"controller", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoNet.SdkController controller
    {
      get { return _controller; }
      set { _controller = value; }
    }
    private ProtoNet.PosBrife _posBrife;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"posBrife", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoNet.PosBrife posBrife
    {
      get { return _posBrife; }
      set { _posBrife = value; }
    }
    private bool _agree;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"agree", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool agree
    {
      get { return _agree; }
      set { _agree = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResNotifyGameRoomDissolution")]
  public partial class ResNotifyGameRoomDissolution : global::ProtoBuf.IExtensible
  {
    public ResNotifyGameRoomDissolution() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResNotifyGameOver")]
  public partial class ResNotifyGameOver : global::ProtoBuf.IExtensible
  {
    public ResNotifyGameOver() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqGetRoomInfo")]
  public partial class ReqGetRoomInfo : global::ProtoBuf.IExtensible
  {
    public ReqGetRoomInfo() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResGetRoomInfo")]
  public partial class ResGetRoomInfo : global::ProtoBuf.IExtensible
  {
    public ResGetRoomInfo() {}
    
    private ProtoNet.ResponseResult _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoNet.ResponseResult result
    {
      get { return _result; }
      set { _result = value; }
    }
    private ProtoNet.RoomInfo _roomInfo = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"roomInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoNet.RoomInfo roomInfo
    {
      get { return _roomInfo; }
      set { _roomInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResNotifySomeOneGameReady")]
  public partial class ResNotifySomeOneGameReady : global::ProtoBuf.IExtensible
  {
    public ResNotifySomeOneGameReady() {}
    
    private string _roomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private ProtoNet.SdkController _controller;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"controller", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoNet.SdkController controller
    {
      get { return _controller; }
      set { _controller = value; }
    }
    private ProtoNet.PosBrife _posBrife;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"posBrife", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoNet.PosBrife posBrife
    {
      get { return _posBrife; }
      set { _posBrife = value; }
    }
    private bool _ready;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"ready", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool ready
    {
      get { return _ready; }
      set { _ready = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqChangeOnlineStatus")]
  public partial class ReqChangeOnlineStatus : global::ProtoBuf.IExtensible
  {
    public ReqChangeOnlineStatus() {}
    
    private bool _online;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"online", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool online
    {
      get { return _online; }
      set { _online = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResChangeOnlineStatus")]
  public partial class ResChangeOnlineStatus : global::ProtoBuf.IExtensible
  {
    public ResChangeOnlineStatus() {}
    
    private ProtoNet.ResponseResult _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoNet.ResponseResult result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResNotifySomeOneChangeOnlineStatus")]
  public partial class ResNotifySomeOneChangeOnlineStatus : global::ProtoBuf.IExtensible
  {
    public ResNotifySomeOneChangeOnlineStatus() {}
    
    private string _roomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private ProtoNet.SdkController _controller;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"controller", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoNet.SdkController controller
    {
      get { return _controller; }
      set { _controller = value; }
    }
    private ProtoNet.PosBrife _posBrife;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"posBrife", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoNet.PosBrife posBrife
    {
      get { return _posBrife; }
      set { _posBrife = value; }
    }
    private bool _online;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"online", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool online
    {
      get { return _online; }
      set { _online = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResNotifyBigCalculatePanel")]
  public partial class ResNotifyBigCalculatePanel : global::ProtoBuf.IExtensible
  {
    public ResNotifyBigCalculatePanel() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqCorrectTimer")]
  public partial class ReqCorrectTimer : global::ProtoBuf.IExtensible
  {
    public ReqCorrectTimer() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResCorrectTimer")]
  public partial class ResCorrectTimer : global::ProtoBuf.IExtensible
  {
    public ResCorrectTimer() {}
    
    private ProtoNet.ResponseResult _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoNet.ResponseResult result
    {
      get { return _result; }
      set { _result = value; }
    }
    private long _leftDissolutionTimer = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"leftDissolutionTimer", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long leftDissolutionTimer
    {
      get { return _leftDissolutionTimer; }
      set { _leftDissolutionTimer = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqQuickChangeRoom")]
  public partial class ReqQuickChangeRoom : global::ProtoBuf.IExtensible
  {
    public ReqQuickChangeRoom() {}
    
    private string _pipeiParam = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"pipeiParam", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string pipeiParam
    {
      get { return _pipeiParam; }
      set { _pipeiParam = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResQuickChangeRoom")]
  public partial class ResQuickChangeRoom : global::ProtoBuf.IExtensible
  {
    public ResQuickChangeRoom() {}
    
    private ProtoNet.ResponseResult _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoNet.ResponseResult result
    {
      get { return _result; }
      set { _result = value; }
    }
    private int _operate = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"operate", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int operate
    {
      get { return _operate; }
      set { _operate = value; }
    }
    private int _roomType = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"roomType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int roomType
    {
      get { return _roomType; }
      set { _roomType = value; }
    }
    private ProtoNet.ServerInfoIpsSafeDetail _bestServerInfo = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"bestServerInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoNet.ServerInfoIpsSafeDetail bestServerInfo
    {
      get { return _bestServerInfo; }
      set { _bestServerInfo = value; }
    }
    private string _roomId = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoNet.ServerInfoIpsSafeDetail> _logicDetails = new global::System.Collections.Generic.List<ProtoNet.ServerInfoIpsSafeDetail>();
    [global::ProtoBuf.ProtoMember(6, Name=@"logicDetails", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoNet.ServerInfoIpsSafeDetail> logicDetails
    {
      get { return _logicDetails; }
    }
  
    private int _gameId = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"gameId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gameId
    {
      get { return _gameId; }
      set { _gameId = value; }
    }
    private int _timesType = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"timesType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int timesType
    {
      get { return _timesType; }
      set { _timesType = value; }
    }
    private int _changeServer;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"changeServer", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int changeServer
    {
      get { return _changeServer; }
      set { _changeServer = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResNotifySomeOneChangeRobot")]
  public partial class ResNotifySomeOneChangeRobot : global::ProtoBuf.IExtensible
  {
    public ResNotifySomeOneChangeRobot() {}
    
    private int _isRobot;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"isRobot", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int isRobot
    {
      get { return _isRobot; }
      set { _isRobot = value; }
    }
    private string _uniqueId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"uniqueId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string uniqueId
    {
      get { return _uniqueId; }
      set { _uniqueId = value; }
    }
    private int _pos;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResNotifyChangeToOldRoom")]
  public partial class ResNotifyChangeToOldRoom : global::ProtoBuf.IExtensible
  {
    public ResNotifyChangeToOldRoom() {}
    
    private ProtoNet.ServerInfoIpsSafeDetail _bestServerInfo = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"bestServerInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoNet.ServerInfoIpsSafeDetail bestServerInfo
    {
      get { return _bestServerInfo; }
      set { _bestServerInfo = value; }
    }
    private string _roomId = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private int _gameId = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"gameId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gameId
    {
      get { return _gameId; }
      set { _gameId = value; }
    }
    private int _timesType = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"timesType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int timesType
    {
      get { return _timesType; }
      set { _timesType = value; }
    }
    private int _roomType = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"roomType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int roomType
    {
      get { return _roomType; }
      set { _roomType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqSitDown")]
  public partial class ReqSitDown : global::ProtoBuf.IExtensible
  {
    public ReqSitDown() {}
    
    private int _pos = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResSitDown")]
  public partial class ResSitDown : global::ProtoBuf.IExtensible
  {
    public ResSitDown() {}
    
    private ProtoNet.ResponseResult _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoNet.ResponseResult result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResNotifySomeOneSitDown")]
  public partial class ResNotifySomeOneSitDown : global::ProtoBuf.IExtensible
  {
    public ResNotifySomeOneSitDown() {}
    
    private int _pos;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private ProtoNet.SdkController _controller;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"controller", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoNet.SdkController controller
    {
      get { return _controller; }
      set { _controller = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqStandUp")]
  public partial class ReqStandUp : global::ProtoBuf.IExtensible
  {
    public ReqStandUp() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResStandUp")]
  public partial class ResStandUp : global::ProtoBuf.IExtensible
  {
    public ResStandUp() {}
    
    private ProtoNet.ResponseResult _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoNet.ResponseResult result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResNotifySomeOneStandUp")]
  public partial class ResNotifySomeOneStandUp : global::ProtoBuf.IExtensible
  {
    public ResNotifySomeOneStandUp() {}
    
    private int _pos;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private ProtoNet.SdkController _controller;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"controller", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoNet.SdkController controller
    {
      get { return _controller; }
      set { _controller = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResNotifySomeOneEnterCharge")]
  public partial class ResNotifySomeOneEnterCharge : global::ProtoBuf.IExtensible
  {
    public ResNotifySomeOneEnterCharge() {}
    
    private string _uniqueIds;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uniqueIds", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string uniqueIds
    {
      get { return _uniqueIds; }
      set { _uniqueIds = value; }
    }
    private int _rechargeTime;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"rechargeTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int rechargeTime
    {
      get { return _rechargeTime; }
      set { _rechargeTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResNotifyAccountsChange")]
  public partial class ResNotifyAccountsChange : global::ProtoBuf.IExtensible
  {
    public ResNotifyAccountsChange() {}
    
    private string _uniqueId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uniqueId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string uniqueId
    {
      get { return _uniqueId; }
      set { _uniqueId = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoNet.PlayerAccount> _counts = new global::System.Collections.Generic.List<ProtoNet.PlayerAccount>();
    [global::ProtoBuf.ProtoMember(2, Name=@"counts", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoNet.PlayerAccount> counts
    {
      get { return _counts; }
    }
  
    private string _extendStr = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"extendStr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string extendStr
    {
      get { return _extendStr; }
      set { _extendStr = value; }
    }
    private int _charge = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"charge", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int charge
    {
      get { return _charge; }
      set { _charge = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResNotifyChargeOver")]
  public partial class ResNotifyChargeOver : global::ProtoBuf.IExtensible
  {
    public ResNotifyChargeOver() {}
    
    private string _uniqueId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uniqueId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string uniqueId
    {
      get { return _uniqueId; }
      set { _uniqueId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqWatherList")]
  public partial class ReqWatherList : global::ProtoBuf.IExtensible
  {
    public ReqWatherList() {}
    
    private int _length;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"length", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int length
    {
      get { return _length; }
      set { _length = value; }
    }
    private int _paixu;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"paixu", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int paixu
    {
      get { return _paixu; }
      set { _paixu = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResWatherList")]
  public partial class ResWatherList : global::ProtoBuf.IExtensible
  {
    public ResWatherList() {}
    
    private ProtoNet.ResponseResult _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoNet.ResponseResult result
    {
      get { return _result; }
      set { _result = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoNet.SdkController> _sdkControllers = new global::System.Collections.Generic.List<ProtoNet.SdkController>();
    [global::ProtoBuf.ProtoMember(2, Name=@"sdkControllers", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoNet.SdkController> sdkControllers
    {
      get { return _sdkControllers; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqOnceMore")]
  public partial class ReqOnceMore : global::ProtoBuf.IExtensible
  {
    public ReqOnceMore() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResOnceMore")]
  public partial class ResOnceMore : global::ProtoBuf.IExtensible
  {
    public ResOnceMore() {}
    
    private ProtoNet.ResponseResult _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoNet.ResponseResult result
    {
      get { return _result; }
      set { _result = value; }
    }
    private int _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private string _roomId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResNotifyOnceMore")]
  public partial class ResNotifyOnceMore : global::ProtoBuf.IExtensible
  {
    public ResNotifyOnceMore() {}
    
    private ProtoNet.ResponseResult _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoNet.ResponseResult result
    {
      get { return _result; }
      set { _result = value; }
    }
    private int _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private string _roomId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"reqLogicServerTime")]
  public partial class reqLogicServerTime : global::ProtoBuf.IExtensible
  {
    public reqLogicServerTime() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"resLogicServerTime")]
  public partial class resLogicServerTime : global::ProtoBuf.IExtensible
  {
    public resLogicServerTime() {}
    
    private ProtoNet.ResponseResult _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoNet.ResponseResult result
    {
      get { return _result; }
      set { _result = value; }
    }
    private long _serverTime = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"serverTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long serverTime
    {
      get { return _serverTime; }
      set { _serverTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}