
º"
MsgCode.protoProtoNet"<
ResponseResult
code (
success (
msg (	"?
PlayerAccount
type (
count (
	bankcount ("0
ResNotifyAlert
msg (	
	extendStr (	"H
ResNotifyDissolutionConnect
gameId (
type (
msg (	"Ç
ResNotifyChatArrive
msgId (	
msgType (
msg (	
chanel (
msgCreateTime (
fromUniqueId (	
pos (
fromControllerNick (	
fromControllerHeadurl	 (	"3
ResChat(
result (2.ProtoNet.ResponseResult"[
ReqChat
msgType (
msg (	
chanel (

toUniqueId (	
clubId (	"
ResNotifyBeKickOut" 
ResExceptionCatch
msg (	"6
ResConnectCreat
now (
heartbeartTime ("
ReqHeartBeat"
ResHeartBeat
time (*N
RoomType
	GOLD_ROOM
	CARD_ROOM

MATCH_ROOM
SHANGZHUANG_ROOM*¾
GameCode
REQ_GET_MATCH_LISTßÜ*
RES_GET_MATCH_LISTÞÜ*
REQ_SIGNUP_MATCHÝÜ*
RES_SIGNUP_MATCHÜÜ*
RES_NOTIFY_ENTER_MATCHÛÜ*
REQ_CANLE_SIGN_MATCHÚÜ*
RES_CANLE_SIGN_MATCHÙÜ**
$RES_NOTIFY_MATCHROOM_WAITTING_CHANGEØÜ*
RES_NOTIFY_TIMES_OVER×Ü*
REQ_CONTINUE_MATCHÖÜ*
RES_CONTINUE_MATCHÕÜ*
REQ_GATE_LOGINŸ÷6
RES_GATE_LOGINž÷6
REQ_GET_ACCOUNTINFO÷6
RES_GET_ACCOUNTINFOœ÷6
REQ_GET_GAMEZONEINFO_LIST›÷6
RES_GET_GAMEZONEINFO_LISTš÷6
REQ_GET_GAMEZONE_DETAIL™÷6
RES_GET_GAMEZONE_DETAIL˜÷6
REQ_JOIN_LOGIC_GAMEROOM—÷6
RES_JOIN_LOGIC_GAMEROOM–÷6
REQ_QUICK_JOIN_GAMEROOM•÷6
RES_QUICK_JOIN_GAMEROOM”÷6#
RES_NOTIFY_BROAD_PLAT_MARQUEE“÷6!
RES_NOTIFY_SELF_DATA_CHANGE’÷6
REQ_GET_ROOMBRIFE_LIST‘÷6
RES_GET_ROOMBRIFE_LIST÷6
REQ_CHECK_IN_MATCH÷6
RES_CHECK_IN_MATCHŽ÷6
REQ_OPEN_ROOM_REPLACE÷6
RES_OPEN_ROOM_REPLACEŒ÷6'
!REQ_OPEN_ROOM_REPLACE_RECORD_LIST‹÷6'
!RES_OPEN_ROOM_REPLACE_RECORD_LISTŠ÷6'
!REQ_DISSOLUTION_OPEN_ROOM_REPLACE‰÷6'
!RES_DISSOLUTION_OPEN_ROOM_REPLACEˆ÷6
REQ_GAME_ROOM_LIST‡÷6
RES_GAME_ROOM_LIST†÷6
REQ_CLUB_GAME_ROOM_LIST…÷6
RES_CLUB_GAME_ROOM_LIST„÷6
REQ_CLUB_PIPEI_ROOMƒ÷6
RES_CLUB_PIPEI_ROOM‚÷6
REQ_EXIT_CLUB_PIPEI_ROOM÷6
RES_EXIT_CLUB_PIPEI_ROOM€÷6 
REQ_CLUB_PIPEI_ROOM_STATUSÿö6 
RES_CLUB_PIPEI_ROOM_STATUSþö6
RES_NOTIFY_CLUB_PIPEI_SUCýö6,
&RES_NOTIFY_REFRESH_CLUB_GAME_ROOM_LISTüö6*
$RES_NOTIFY_REFRESH_CLUB_RED_BOT_NEWSûö6
RES_NOTIFY_CLUB_DISMISSúö6 
RES_NOTIFY_CLUB_KICKED_OUTùö6&
 RES_NOTIFY_CLUB_CHANGE_GAME_TYPEøö6
REQ_LOGIC_LOGINÿé0
RES_LOGIC_LOGINþé0
REQ_CREATE_GAMEROOMýé0
RES_CREATE_GAMEROOMüé0 
RES_NOTIFY_GAMEROOM_CREATEûé0
REQ_JOIN_GAMEROOMúé0
RES_JOIN_GAMEROOMùé0&
 RES_NOTIFY_SOMEONE_JOIN_GAMEROOMøé0
REQ_EXIT_GAMEROOM÷é0
RES_EXIT_GAMEROOMöé0&
 RES_NOTIFY_SOMEONE_EXIT_GAMEROOMõé0
REQ_GAME_READYôé0
RES_GAME_READYóé0
REQ_DISSOLUTION_GAMEROOMïé0
RES_DISSOLUTION_GAMEROOMîé01
+RES_NOTIFY_SOMEONE_REQ_DISSOLUTION_GAMEROOMíé0$
REQ_AGREE_DISSOLUTION_GAMEROOMìé0$
RES_AGREE_DISSOLUTION_GAMEROOMëé03
-RES_NOTIFY_SOMEONE_AGREE_DISSOLUTION_GAMEROOMêé0%
RES_NOTIFY_GAMEROOM_DISSOLUTIONéé0
RES_NOTIFY_GAMEOVERèé0
REQ_GET_ROOM_INFOçé0
RES_GET_ROOM_INFOæé0#
RES_NOTIFY_SOMEONE_GAME_READYåé0
REQ_CHANGE_ONLINE_STATUSäé0
RES_CHANGE_ONLINE_STATUSãé0-
'RES_NOTIFY_SOMEONE_CHANGE_ONLINE_STATUSâé0$
RES_NOTIFY_BIG_CALCULATE_PANELáé0
REQ_CORRECT_TIMERÞé0
RES_CORRECT_TIMERÝé0
REQ_QUICK_CHANGE_ROOMÜé0
RES_QUICK_CHANGE_ROOMÛé0%
RES_NOTIFY_SOMEONE_CHANGE_ROBOTÚé0"
RES_NOTIFY_CHANGE_TO_OLDROOMÙé0
REQ_SIT_DOWNØé0
RES_SIT_DOWN×é0!
RES_NOTIFY_SOMEONE_SIT_DOWNÖé0
REQ_STAND_UPÕé0
RES_STAND_UPÔé0!
RES_NOTIFY_SOMEONE_STAND_UPÓé0%
RES_NOTIFY_SOMEONE_ENTER_CHARGEÒé0 
RES_NOTIFY_ACCOUNTS_CHANGEÑé0
RES_NOTIFY_CHARGE_OVERÐé0
REQ_WATCHER_LISTÏé0
RES_WATCHER_LISTÎé0
REQ_ONCE_MOREÌé0
RES_ONCE_MOREÍé0
RES_ONOTIFY_ONCE_MOREËé0
REQ_LOGIC_SERVER_TIMEÊé0
RES_LOGIC_SERVER_TIMEÉé0
REQ_SEAT_DOWN·è0
RES_SEAT_DOWN¶è0
REQ_BE_WATHERµè0
RES_BE_WATHER´è0
RES_NOTIFY_ADD_WATHER³è0
RES_NOTIFY_REMOVE_WATHER²è0$
RES_NOTIFY_DISSOLUTION_CONNECT¶„=
RES_NOTIFY_CHAT_ARRIVE·„=
RES_CHAT¸„=
REQ_CHAT¹„=
RES_NOTIFY_BE_KICK_OUTº„=
RES_EXCEPTION_CATCH»„=
RES_HEART_BEAT¼„=
REQ_HEART_BEAT½„=
RES_CONNECT_CREATE¾„=
RES_NOTIFY_ALERT¿„=B
com.version.protobuf.pb